### PR TITLE
Fix OMP setup and 'setmask'

### PR DESCRIPTION
**Pull request by dabail10**
For detailed information about submitting Pull Requests (PRs) to the CICE-Consortium,
please refer to: <https://github.com/CICE-Consortium/About-Us/wiki/Resource-Index#information-for-developers>

## PR checklist
- [X] Short (1 sentence) summary of your PR: 
This is just a simple fix for the OMP ORDERED issue in CESM. This also fixes the issue #805 to deal with grid_type = 'setmask'.
- [X] Developer(s):
dabail10 (D. Bailey)
- [X] Suggest PR reviewers from list in the column to the right.
- [X] Please copy the PR test results link or provide a summary of testing completed below.
Tested in the CESM aux_cice suite. Also ran the base_suite on cheyenne with intel, gnu, and pgi. Everything bfb.
https://github.com/CICE-Consortium/Test-Results/wiki/cice_by_hash_forks#d7988c940a8e2dad95f7b743c521558bba39ef2b
- How much do the PR code changes differ from the unmodified code? 
    - [X] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [X] No
- Does this PR update the Icepack submodule?  If so, the Icepack submodule must point to a hash on Icepack's main branch.
    - [ ] Yes
    - [X] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [X] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [ ] Yes
    - [X] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [X] No 
- [X] Please provide any additional information or relevant details below:
Simply move the flush_fileunit call. This fixes Issue #800 and issue #805. Adds an option for grid_format = 'meshnc'.

### CODE REVIEW

**Review by apcraig — APPROVED** [review]

**Comment by dabail10** [comment]
What happened here? Oh shoot. I committed the meshgrid fixes to cesm_updates as well. Would it be ok to add both in one PR?

**Comment by apcraig** [comment]
I think it's fine.  The two changes are both pretty small.  Please update the documentation as needed and update the PR title and description a bit.  Please also run some test suites with the new code changes.  Thanks.

If you prefer to have a separate PR, that's also fine.

**Comment by dabail10** [comment]
Running the test suite again.

**Comment by dabail10** [comment]
This is ready to go. Bfb with the base_suite on cheyenne with intel/gnu/pgi.

**Review by apcraig — APPROVED** [review]

**Pull request merged**
