### PR TITLE
RASM test update, new bathymetry popfile method, minor refactor to ice_dyn_evp_1d

### PR DESCRIPTION
**Pull request by apcraig**
## PR checklist
- [X] Short (1 sentence) summary of your PR: 
    Test in RASM and update
- [X] Developer(s): 
    apcraig
- [X] Suggest PR reviewers from list in the column to the right.
- [X] Please copy the PR test results link or provide a summary of testing completed below.
    Tested on izumi, 4 compilers vs current master,
    #c21d34b37 at https://github.com/CICE-Consortium/Test-Results/wiki/cice_by_hash_forks
- How much do the PR code changes differ from the unmodified code? 
    - [X] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [X] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [X] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [ ] Yes
    - [X] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [X] No 
- [X] Please provide any additional information or relevant details below:

Merge three ice_dyn_evp_1d modules to one module and update ice_dyn_evp_1d interface names.  
Add get_bathymetry_popfile from RASM, turned off by default
Fix circular logic issue that only was created with CESMCOUPLED turned on

### CODE REVIEW

**Comment by apcraig** [comment]
@phil-blain, my hope is this addresses #366.  I think it's worth a quick test on your end with the nemo3.6 system.  If other changes are needed and they are not extensive, maybe we can include them in this PR.  If it looks like more work to get CICE working with nemo3.6, then maybe another PR is needed.  We can decide once we have more info.  thanks!

**Comment by apcraig** [comment]
@duvivier, it looks like the read-the-docs is failing due to a python version issue.  Does this make any sense to you?  If I login to readthedocs, it looks like this failure started at least 3 days ago and is not related to the current PR in particular.  It looks like it's something to do with bibtex, but I could be wrong.

**Comment by apcraig** [comment]
regarding readthedocs issues, maybe we need to add a configuration file and shift to v2?

[https://docs.readthedocs.io/en/stable/config-file/index.html](https://docs.readthedocs.io/en/stable/config-file/index.html)

**Comment by duvivier** [comment]
@apcraig thanks for bringing this up. It's irritating that it worked just fine last week and now something has changed on that end that's making it fail. Let me look into it a bit. I'll try just a normal build on the master branch first to see if that's broken too.

**Comment by apcraig** [comment]
@phil-blain, glad to hear we've addressed at least one of the nemo build issues.  We can make other changes if needed in the future.

I can clean up the old commented out code.  This code was provided by DMI and in these cases, I sometimes think it's nice to keep the old code around to see the changes and maybe compare to any updates on their end moving forward.  I don't know if that's helpful in this case or not.  You're probably right that I should maybe clean that up.

**Comment by apcraig** [comment]
thanks @duvivier.  I'm happy to help do some googling/testing/etc if you hit a wall or have other high priority tasks.  Just let me know.

**Comment by duvivier** [comment]
@apcraig sorry I've been slow. I just had other meetings/telecons today that have hampered focusing on this. I will try tonight or tomorrow, but if that's holding things up please feel free to google etc. Sorry.

**Comment by apcraig** [comment]
@duvivier, no worries, no rush.  Thanks for having a look!

**Comment by dabail10** [comment]
I know there is build the docs problems, but the code looks good to me.

**Comment by duvivier** [comment]
@apcraig I have determined this is an issue in general with all our documentation (not just this PR). 
 It looks to me like the issue is doc/requirements.txt and that we need to change the sphinxcontrib-bibtex. Something with the changes in python versions. It's irritating that this isn't backwards compatible. But anyway. 

I'm starting a new development branch to try and figure it out.

**Comment by apcraig** [comment]
Thanks @duvivier!  I am quite confident that this PR is not introducing a problem, it broader.  At this point, I think we should ignore the failing readthedocs check and let this (and other work) move forward at its pace.  We will fix the readthedocs as a separate PR.  I guess we have to fix the readthedocs before we release, so that's really the target we should be thinking about.  Thanks again, keep me posted.

**Comment by duvivier** [comment]
@apcraig I think I solved it. It had to do with the settings in the consortium RTD. Under "Advanced Settings" there is a python interpreter choice. We had Python 2.x chosen, but I just switched it to 3.x and it seems to work now. 

In requirements.txt we call sphinxcontrib-bibtex. We don't specify a version, so it just calls the latest version. I just checked and it appears they had a release on Sept.20. My guess is that the newest release stopped support for python v.2 and started support for python v.3.

**Comment by duvivier** [comment]
@apcraig I am trying to figure out how to re-trigger the documentation build for this PR in RTD, but I can't figure it out. At any rate, I think you should go ahead and merge this into the master and then the master documentation should build properly with the change I introduced in the RTD settings for the consortium.

**Comment by apcraig** [comment]
@duvivier Excellent, thank you!  I am looking to retrigger the build too.  I may just push a small change to PR if I can't figure it out either.

**Comment by duvivier** [comment]
@apcraig This looks like it did the trick for the RTD tests.

**Comment by apcraig** [comment]
I cleaned up the old code as suggested by @phil-blain, that triggered new builds and readthedocs is passing again!  Thanks @duvivier

**Comment by phil-blain** [comment]
The travis build is failing due to the NCAR ftp download. 

For future reference, another way to trigger a new build is by pushing an empty commit : 
`git commit --allow-empty -m ''Trigger Travis"`, or amending the last commit:
 `git commit --amend`, changing nothing and force-pushing.

**Comment by duvivier** [comment]
@phil-blain It looks like you (or @apcraig ) retriggered the travis build. Nothing has changed on the NCAR side, so I'm not sure why this occasionally comes up. I will look into moving the ftp data as we've discussed but not till after the next release. Also the JRA55 data nearly doubled the size, so that may become an issue too.

**Comment by apcraig** [comment]
The travis build can be retriggered manually and I have done that.  The readthedocs doesn't seem to have that capability yet.  Good to know about the empty git push option.

I will merge this later today unless I hear other concerns.

**Pull request merged**
