### PR TITLE
doc mods for CICE release

### PR DESCRIPTION
**Pull request by duvivier**
Finalizing documentation for CICE (and Icepack) releases. This will be done in stages, but I want to start a PR so it's easier to compare the rst changes.

- Developer(s): Alice DuVivier w/ Contribution from @eclare108213 

- Please suggest code Pull Request reviewers in the column at right.

- Are the code changes bit for bit, different at roundoff level, or more substantial? bit for bit

- Please include the link to test results or paste the summary block from the bottom of the testing output below.

- Does this PR create or have dependencies on Icepack or any other models? Yes (Icepack documentation)

- Is the documentation being updated with this PR? (Y/N) Y

Here is the readthedocs test of the documentation changes:
https://cice.readthedocs.io/en/latest/index.html

### CODE REVIEW

**Comment by duvivier** [comment]
I have updated the second set of mods based on conversations with @eclare108213 going on under issue #244 

See new documentation:
https://cice.readthedocs.io/en/latest/index.html
https://media.readthedocs.org/pdf/cice/latest/cice.pdf

**Comment by duvivier** [comment]
@apcraig I have two particular questions:

In ug_running.rst, Elizabeth said this didn't make sense to her:
>The version should be some like n.m.p.string.
I'm not sure how else we'd want to re-word it. Any thoughts?

In ug_troubleshooting.rst, is the discussion of BARRIERS still correct?
>In some configurations, multiple calls to scatter or gather global variables may overfill MPI’s buffers, causing the code to slow down (particularly when writing large output files such as restarts). To remedy this problem, set BARRIERS yes in cice.settings. This synchronizes MPI messages, keeping the buffers in check.

**Comment by duvivier** [comment]
@eclare108213  I propose we go ahead and merge this as it is. I think we still need to do a little bit more in the user's guide section (e.g. sections 3.2, 3.3 and 3.3.5 in particular) and will likely have a few more things as well. But there are a lot of changes at this point and I think it makes sense to merge them and then we can continue editing from there.

**Comment by eclare108213** [comment]
I agree.  We can remove BARRIERS and CAM_ICE from the documentation for this release and clean up the code later.

**Comment by eclare108213** [comment]
Please change Los Alamos National Security to Triad National Security in the documentation footers for both CICE and Icepack.

**Pull request merged**
