### PR TITLE
Update box test options

### PR DESCRIPTION
**Pull request by apcraig**
## PR checklist
- [X] Short (1 sentence) summary of your PR: 
    Update box tests
- [X] Developer(s): 
    apcraig
- [X] Suggest PR reviewers from list in the column to the right.
- [X] Please copy the PR test results link or provide a summary of testing completed below.
    Results are bit-for-bit on cheyenne with 3 compilers.  Some test names changed, a random handful were compared to prior results manually and are also bit-for-bit.  A few tests are new.  https://github.com/CICE-Consortium/Test-Results/wiki/cice_by_hash_forks#0bd06542eb9de37bb37b9ddfcf2bd701e07fa941
- How much do the PR code changes differ from the unmodified code? 
    - [X] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [X] No
- Does this PR update the Icepack submodule?  If so, the Icepack submodule must point to a hash on Icepack's main branch.
    - [ ] Yes
    - [X] No
- Does this PR add any new test cases?
    - [X] Yes
    - [ ] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [X] Yes
    - [ ] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [ ] No 
- [X] Please provide any additional information or relevant details below:

- refactor options boxsym and boxislands to boxopen, boxclosed, and boxforce
- update box test names as needed
- update calculation of test suite failures in cice.results.csh
- add documentation to user guide for rectangular grids

### CODE REVIEW

**Comment by apcraig** [comment]
Closes #770.  
Closes #757.  
Addresses some tasks in #660.

**Comment by phil-blain** [comment]
> Closes https://github.com/CICE-Consortium/CICE/issues/757.

Thanks for addressing!

**Review by eclare108213 — APPROVED** [review]
Awesome, thank you.

**Comment by apcraig** [comment]
Should have closed the issues, not sure why it didn't.  Sometimes it works, sometimes not.  I'll do it manually now.

**Comment by phil-blain** [comment]
The "Closes" mentions have to be in the PR description itself (or in a commit message).

It does not work in subsequent comments on the PR.

**Pull request merged**
