### PR TITLE
Add sw_redist option to CICE

### PR DESCRIPTION
**Pull request by dabail10**
For detailed information about submitting Pull Requests (PRs) to the CICE-Consortium,
please refer to: <https://github.com/CICE-Consortium/About-Us/wiki/Resource-Index#information-for-developers>

## PR checklist
- [X] Short (1 sentence) summary of your PR: 
This integrates the sw_redist changes from Icepack into CICE.
- [X] Developer(s): 
dabail10 (D. Bailey)
- [X] Suggest PR reviewers from list in the column to the right.
- [X] Please copy the PR test results link or provide a summary of testing completed below.
https://github.com/CICE-Consortium/Test-Results/wiki/cice_by_mach_forks#cheyenne
- How much do the PR code changes differ from the unmodified code? 
    - [X] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [X] Yes
    - [ ] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [X] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [X] Yes
    - [ ] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [ ] No 
- [X] Please provide any additional information or relevant details below:
The alt03 and alt04 test cases have been updated so that ktherm=1 is bfb. The default settings are such that ktherm=2 is bfb. This is the other piece to addressing issue #485 and https://github.com/CICE-Consortium/Icepack/issues/280.

### CODE REVIEW

**Comment by dabail10** [comment]
Yes! This change was already merged in Icepack.

**Comment by apcraig** [comment]
The changes in CICE here are related to turning on the new options in Icepack.  There are 3 new namelist for CICE and these are basically passed to Icepack.  The changes in the alt options preserve the current CICE testing where ktherm=1 sets sw_redist=.true..  That is consistent with the bl99 having this feature hardwired before and mushy not.  As we move forward, we probably want to add a test where mushy turns on the sw_redist feature and bl99 does not to be more complete.

**Comment by apcraig** [comment]
90% of the tests are completed on gordon and everything that has run has passed, https://github.com/CICE-Consortium/Test-Results/wiki/cice_by_hash_forks#91acad70660303035754f32c36eca863f00b29d1.  A few are sitting in the queue, but I'm fairly confident it's all fine.  I will merge this now and then update the test results when they have completed.

**Comment by phil-blain** [comment]
For easier future lookups (it took me a while), here is the corresponding Icepack PR:  CICE-Consortium/Icepack#326

**Pull request merged**
