### PR TITLE
fixing the list in tracer section

### PR DESCRIPTION
**Pull request by duvivier**
Fixing the list for how to add a tracer (see issue #286 ). 

- Developer(s): Alice DuVivier

- Are the code changes bit for bit, different at roundoff level, or more substantial? B4B

- Please include the link to test results or paste the summary block from the bottom of the testing output below.    Tested on laptop sphinx to verify correct formatting.

- Does this PR create or have dependencies on Icepack or any other models? N

- Is the documentation being updated with this PR? (Y/N) Y
If not, does the documentation need to be updated separately at a later time? (Y/N) NA

- Other Relevant Details:

### CODE REVIEW

**Comment by eclare108213** [comment]
travis is failing to get the forcing data from NCAR

**Comment by duvivier** [comment]
@eclare108213 The machine is up and files haven't been changed, so I just rebooted Travis. Hopefully things go smoothly this time.

**Comment by apcraig** [comment]
I triggered travis again and I think it worked this time, but it had to try a few times.  Not sure whether the issue is on the travis or NCAR side, but lets not worry too much unless this starts to happen more frequently.

**Comment by eclare108213** [comment]
@duvivier please remind me...  is the updated documentation available somewhere (in compiled form) or do I need to generate it myself?

**Comment by duvivier** [comment]
@eclare108213 @apcraig - It looks like everything is running smoothly now for Travis. I don't know why these intermittent errors pop up, but I agree that we probably don't have to worry unless a re-trigger of Travis fails too.

@eclare108213 generating RTD documentation is still not supported as part of PR testing, though I know that RTD is working on that. So I modified that file and tested it offline myself as well as did a build on my personal RTD to check. See here:
https://cice.readthedocs.io/en/latest/developer_guide/dg_other.html
Doing that though requires switching branches so that "latest" points at my development branch. It's kind of a pain, so I hope that the automatic testing with a PR is supported ASAP. Any work around Tony or I could find was pretty cludgey, so RTD support is really the thing to wait for. I think they said it would be done by end of 2019.

**Comment by phil-blain** [comment]
Another way is to view your changes on RTD is to add your development branch to you RTD :
1. Go to your RTD account and build any version (ex. latest). This will under the hood do a git fetch so that RTD is aware of your new development branch
2. Activate your development branchL Admin button-> Versions (on the left) -> Tick your development branch
3. RTD should build the doc for your development branch

**Comment by duvivier** [comment]
This is exactly what I do, but I can have multiple development branches and unless you want to set up RTD streams for each (and then delete those after the code is merged) I just point latest at whatever development branch needs testing at the moment.

**Pull request merged**
