### PR TITLE
Fix CESMCOUPLED compile issue in icepack.

### PR DESCRIPTION
**Pull request by dabail10**
For detailed information about submitting Pull Requests (PRs) to the CICE-Consortium,
please refer to: <https://github.com/CICE-Consortium/About-Us/wiki/Resource-Index#information-for-developers>

## PR checklist
- [X] Short (1 sentence) summary of your PR: 
Updates icepack with fix for CESMCOUPLED compile problem.
- [X] Developer(s): 
 dabail10 (D. Bailey)
- [X] Suggest PR reviewers from list in the column to the right.
- [X] Please copy the PR test results link or provide a summary of testing completed below.
Tested within CESM. Does not change CICE standalone. 
- How much do the PR code changes differ from the unmodified code? 
    - [X] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [X] Yes
    - [ ] No
- Does this PR update the Icepack submodule?  If so, the Icepack submodule must point to a hash on Icepack's main branch.
    - [X] Yes
    - [ ] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [X] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [ ] Yes
    - [X] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [X] No 
- [X] Please provide any additional information or relevant details below:

### CODE REVIEW

**Comment by dabail10** [comment]
Not sure why the documentation is being changed here? I checked out Icepack main.

**Comment by apcraig** [comment]
A documentation PR was added to Icepack March 15, had not yet been merged to the CICE main.

I think a bigger question is why you're using such an old branch for this PR, lots of old commits already merged are showing in the PR history, although not in the code changes thankfully.  :)

**Review by apcraig — APPROVED** [review]

**Comment by dabail10** [comment]
The problem is that I just updated the cesm_updates branch from Consortium main today. So, the history is convoluted. I don't like always creating a new branch for each of these updates, but maybe that is what I should be doing. I am trying to keep cesm_updates as my main "trunk" for CESM. Can you do a squash merge here?

**Comment by apcraig** [comment]
I don't think a squash merge is going to help.  This is an issue with your workflow.  You might be able to somehow do a rebase of your cesm_updates branch, but I'm not sure if that's going to work.  You could force push a new version to cesm_updates.  That would work, but it's not ideal overall either, especially since cesm_updates is so critical.

You are using cesm_updates for many purposes.  It sounds like it's what CESM is using, it's also where you develop (some things) and PR to the consortium, and you want it to be synced up with the Consortium.  If you want some ideas about how to do things differently, probably easier to discuss via email.

**Pull request merged**
