### PR TITLE
doc: correct `Pstar` units

### PR DESCRIPTION
**Pull request by phil-blain**
## PR checklist
- [x] Short (1 sentence) summary of your PR: 
    Correct units for `Pstar` in the doc.
- [x] Developer(s): 
    P. Blain
- [x] Suggest PR reviewers from list in the column to the right.
- [x] Please copy the PR test results link or provide a summary of testing completed below.
    No tests; doc changes only.
- How much do the PR code changes differ from the unmodified code? 
    - [x] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [x] Yes https://github.com/CICE-Consortium/Icepack/pull/325
    - [ ] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [x] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [x] Yes
    - [ ] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [ ] No 
- [x] Please provide any additional information or relevant details below:

I checked the units for `Pstar` in Hibler's 1979 paper for CICE-Consortium/CICE#475, but it appears Hibler made a mistake in his table!
@JFLemieux73 pointed that to me offline.

### CODE REVIEW

**Comment by phil-blain** [comment]
@JFLemieux73 I've fixed the RST syntax for `k2`.

@eclare108213 I fixed another occurence of "N/m" for Pstar in `doc/source/cice_index.rst`. 

I went to the output of `git grep --recurse-submodules 'N/m'` and found two occurences in Icepack: the one you note in `sg_mechanical.rst` and another one in `icepack/doc/source/icepack_index.rst:350`.

I'll do a separate Icepack PR for these. Maybe we'll want to merge the Icepack PR so  that this here PR can reference the new Icepack commit ? this would be cleaner, I think.

**Comment by eclare108213** [comment]
Fixing Icepack and merging it with this PR would be cleaner, yes, though not essential.  Either way, thanks for doing this.

**Comment by phil-blain** [comment]
I've just pushed an additional commit updating Icepack to the latest master.

**Comment by apcraig** [comment]
I will run a full test suite with this PR.  Now that icepack is updated, we should do that testing first.

**Comment by phil-blain** [comment]
thanks @apcraig. I agree.

**Comment by apcraig** [comment]
The test results are https://github.com/CICE-Consortium/Test-Results/wiki/cice_by_hash_forks#2e2cb0afe0fa8570d870eafec14c94d3f9d83eaa.  This is fine.  There are several regression failures due to the upgrade in Icepack, but this is expected.  These come from code changes in https://github.com/CICE-Consortium/Icepack/pull/320 and are documented clearly there.

**Pull request merged**
