### PR TITLE
fixing rst errors

### PR DESCRIPTION
**Pull request by duvivier**
For detailed information about submitting Pull Requests (PRs) to the CICE-Consortium,
please refer to: <https://github.com/CICE-Consortium/About-Us/wiki/Resource-Index#information-for-developers>

## PR checklist
- [ X ] Short (1 sentence) summary of your PR: 
    Cleaning up RST files for documentation. In response to issues #335 and #347. @phil-blain  I have questions for you at the bottom here.
- [ X ] Developer(s): 
    @duvivier 
- [ X ] Suggest PR reviewers from list in the column to the right.
- [ X ] Please copy the PR test results link or provide a summary of testing completed below.
   From @duvivier's RTD build of the rstcleanup branch: https://cice.readthedocs.io/en/latest/ 
- How much do the PR code changes differ from the unmodified code? 
    - [ X ] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [ X ] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [ X ] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/.)
    - [ X ] Yes
    - [ ] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [ ] No 
- [ X ] Please provide any additional information or relevant details below:
   @phil-blain please in particular look over these sections that are relevant to the following issues:

   #335 --> https://cice.readthedocs.io/en/latest/user_guide/ug_implementation.html
   - I think I found all of these issues and searching works, but please let me know if you find more. the "\_" only renders badly if it's in a ``X`` special formatting, but not if it's in *X* or **X**

   #347  --> https://cice.readthedocs.io/en/latest/user_guide/ug_testing.html
   - I added your suggestions in the end-to-end section
   - I did not yet add info on the Implementation notes: 1)...2) section. Please suggest what you wanted added there in your review?
   - I haven't yet fixed the link to make it more direct. I need to think a bit more through the path you have. Let's discuss.

### CODE REVIEW

**Comment by phil-blain** [comment]
Concerning the paragraph

> Implementation notes: 1) Provide a pass/fail on each of the confidence intervals, 2) Facilitate output of a bitmap for each test so that locations of failures can be identified.

I thought that it could simply be deleted as it seemed outdated and more of a 'note-to-self' kind.

**Comment by phil-blain** [comment]
Also, I checked out out this branch and did `grep -r '\\_' | grep '``'` and it did not return any cases of '\\_' inside ` ``  ``  ` so I think you got them all.

**Comment by phil-blain** [comment]
As a side note, I think it would be clearer if cice.readthedocs.io and icepack.readthedocs.io were the official versions of the documentation, though I don't know the full history of the implementation/decision. It's not a big issue in my opinion.

**Comment by eclare108213** [comment]
I agree with @phil-blain about deleting the 'implementation notes' paragraph.  Otherwise this looks great to me.  Thank you!

**Comment by duvivier** [comment]
@eclare108213 I just removed the "Implementation Notes" line. I think it's good to go.

@phil-blain We originally used cice.readthedocs.io and icepack.readthedocs.io as the documentation, but we went to RTD for two reasons. 1) we wanted to have a non-changing version of the documentation and PDF for each release, and 2) we would have had to maintain a separate but orphan branch constantly with the documentation on it alone. However, since RTD might force us to implement ads in the future we may need to re-visit this. But for now we should stick with RTD for the immediate future.

**Pull request merged**
