### PR TITLE
Add option to write restarts each time step, add verification for dumpfreq namelist value in ice_init.F90

### PR DESCRIPTION
**Pull request by phil-blain**
Add option to write restarts every time step and add a check in ice_init.F90 to check the dumpfreq value.

- Developer(s): Philippe Blain

- Please suggest code Pull Request reviewers in the column at right. @eclare108213 

- Are the code changes bit for bit, different at roundoff level, or more substantial?
BFB
- Please include the link to test results or paste the summary block from the bottom of the testing output below.
No tests.
- Does this PR create or have dependencies on Icepack or any other models? 
No
- Is the documentation being updated with this PR? (Y/N) Yes
If not, does the documentation need to be updated separately at a later time? (Y/N) No

- Other Relevant Details:

I stumbled upon that when I tried to set dumpfreq to '1' to have restarts at each time step, without checking in the doc if that value was allowed... The model ran fine but no restarts were written at all, so I figured I'd add that option and that check. 

If you feel like that should be an `ERROR` instead of a `WARNING` I can change it.

### CODE REVIEW

**Comment by apcraig** [comment]
Maybe we should add an issue that provides an option to dump restarts each timestep.  It looks like "1" is a valid option for histfreq.  We probably should add that option to dumpfreq.  We can either merge this PR and then deal with it later or update this PR to address the feature.  Thanks for identifying this feature.

**Comment by phil-blain** [comment]
I agree. I can update the PR once we decide if we want to have '1' as an option.

**Comment by apcraig** [comment]
I see no reason not to add it as long as it's straight-forward.  I say we should proceed.  Thanks @phil-blain, If you need any help, let me know.

**Comment by eclare108213** [comment]
It wasn't implemented before because I didn't see a real need for it, but if it's useful for you, then go ahead and implement it.  Thanks!

**Comment by phil-blain** [comment]
Done. I also changed one line of the documentation regarding `histfreq`, since it did not accurately reflect the code in ice_calendar.F90.

**Pull request merged**
