### PR TITLE
Updates for RASM compatibility

### PR DESCRIPTION
**Pull request by apcraig**
Update CICE to support RASM integration.

- Developer(s): tcraig

- Are the code changes bit for bit, different at roundoff level, or more substantial? bit-for-bit

- Does this PR create or have dependencies on Icepack or any other models?  RASM needs updated Icepack as well, does not affect CICE standalone though.

- Is the documentation being updated with this PR? (Y/N) N
If not, does the documentation need to be updated separately at a later time? (Y/N) N

- Other Relevant Details:

Synchronize CICE6 in RASM and in Consortium for pre release testing.  Mostly impacts either cesm driver code or code inside CESMCOUPLED cpp.  A couple minor changes were made to the cice driver code for consistency.  The cice and cesm driver codes are now well aligned.

Tested full suites on conrad with 4 compilers against current trunk and everything is bit-for-bit.  See 925e299 https://github.com/CICE-Consortium/Test-Results/wiki/cice_by_hash_forks.

### CODE REVIEW

**Comment by dabail10** [comment]
I will run this through the NAG compiler on hobart.

**Comment by apcraig** [comment]
@dabail10, It's possible the istep stuff was changed, are you seeing something in particular because I don't see anything in the diffs?  This implementation seems to work in rasm which is based on cesm1.x.  cesm2 might have some differences, not sure.  We might actually have to eventually implement a cesm1 and cesm2 driver.  maybe even a cesm2_nuopc as well.  But we'll take that when it comes.

**Comment by dabail10** [comment]
In the model CICE_InitMod.F90 there is diffs in the declarations. These do not cause problems. Just unused variable messages. I will run it through NAG.

**Comment by apcraig** [comment]
Good point.  I did a few things comparing old and new versions of the code.  Basically, I took the cice driver and modified it as needed for RASM and dropped it into the cesm driver directory.  I think it's handy for the two files to be as much alike as possible and only have needed differences.  It could be that I got something wrong or that there are some things from the cice driver that are not needed in the cesm driver.  I guess my preference is to keep them the same as much as possible because I think it will make them easier to keep synchronized.

**Comment by dabail10** [comment]
It occurred to me that I can't really run the RASM driver through NAG. I'll eventually have to work on the CESM driver as well. So, this is probably fine as is.

**Comment by apcraig** [comment]
Yes, this includes an update to the icepack code.  I pushed a one line change over the weekend to the icepack master.

**Comment by eclare108213** [comment]
@dabail10 are you satisfied with this PR or do we still need to clean up some variables?

**Comment by dabail10** [comment]
I'm fine with this. I can't run the CESM driver changes through the NAG compiler yet.

**Pull request merged**
