### PR TITLE
Update dEdd implementation

### PR DESCRIPTION
**Pull request by apcraig**
## PR checklist
- [X] Short (1 sentence) summary of your PR: 
    Update dEdd implementation with fixes
- [X] Developer(s): 
    apcraig, eclare108213
- [X] Suggest PR reviewers from list in the column to the right.
- [X] Please copy the PR test results link or provide a summary of testing completed below.
    bit-for-bit on cheyenne full test suite except alt04, https://github.com/CICE-Consortium/Test-Results/wiki/cice_by_hash_forks#007fbff9b1012b4fb1e447141a888d18b6c24d19
- How much do the PR code changes differ from the unmodified code? 
    - [X] bit for bit, except alt04 (expected)
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [X] Yes, but only because we want to update Icepack because it has several fixes
    - [ ] No
- Does this PR update the Icepack submodule?  If so, the Icepack submodule must point to a hash on Icepack's main branch.
    - [X] Yes
    - [ ] No
- Does this PR add any new test cases?
    - [X] Yes
    - [ ] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [ ] Yes
    - [X] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [X] No 
- [X] Please provide any additional information or relevant details below:

- Update Icepack with several fixes (changes answers for tr_aero)
- Update bgc aerosol table to higher precision
- Add modal aerosol tests
- Update test suites

### CODE REVIEW

**Comment by apcraig** [comment]
This is a draft PR, it is waiting for https://github.com/CICE-Consortium/Icepack/pull/400 then I'll update the Icepack revision in this PR.

**Review by eclare108213 — COMMENTED** [review]
This looks fine to me.  @njeffery could you check whether the namelist parameter set in the modified bgcz(m) test (the set_nml.bgczm file) makes sense?  And does the set_nml.modal test make sense, or do more things need to be turned on/set?

**Comment by apcraig** [comment]
I'm retesting now with the updated Icepack, but confirmed that the new version and the version I was testing are identical.  I don't expect any problems.  This is ready for review and merge.

**Comment by apcraig** [comment]
Full test suite passes, we should review and merge this.

**Review by eclare108213 — APPROVED** [review]

**Pull request merged**
