### PR TITLE
Update KE diagnostic

### LINKED ISSUE #734: kinetic energy diagnostic mixes T and U variables for B grid

### PR DESCRIPTION
**Pull request by apcraig**
## PR checklist
- [X] Short (1 sentence) summary of your PR: 
   Update KE diagnostic
- [X] Developer(s): 
    apcraig
- [X] Suggest PR reviewers from list in the column to the right.
- [X] Please copy the PR test results link or provide a summary of testing completed below.
    Full test suite passes, all results bit-for-bit except KE, rms ice speed, and max speed on C-grid in log files.  https://github.com/CICE-Consortium/Test-Results/wiki/cice_by_hash_forks#db254c11ba0a96b10f875a2d2003ec6aa9298073
- How much do the PR code changes differ from the unmodified code? 
    - [X] bit for bit science, a few diagnostics changed
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [X] No
- Does this PR update the Icepack submodule?  If so, the Icepack submodule must point to a hash on Icepack's main branch.
    - [ ] Yes
    - [X] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [X] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [ ] Yes
    - [X] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [X] No 
- [X] Please provide any additional information or relevant details below:

Update KE diagnostic
- Average U and V fields to T grid for KE calculation for B, C, and CD grid, raw U and V were combined with T grid variables in prior implementation.

Also
- Update max speed calculation for C grid, calc speed at both E and N points
- Refactor highfreq option u,v passed into icepack for windstress calculation
  - This is bit-for-bit
  - Create local variables uvelT_icep and vvelT_icep to store highfreq info
  - Compute [uvelT,vvelT]_icep at start of therm calc instead of end of dynamics calc
  - No longer need to recalc [uvelT,vvelT]_icep on restart
- Update some indentation in ice_diagnostics.F90

Closes #734
See also #655

### CODE REVIEW

**Review by eclare108213 — APPROVED** [review]
This might break restarts from previous-version restart files, but that will be fine going forward and otherwise it looks good.  Thanks for cleaning this up.

**Comment by apcraig** [comment]
This doesn't affect prior restarts.  Nothing has changed on the restart file.  With this update, we just compute two derived quantities in a different place, but it's still there.

**Comment by apcraig** [comment]
Test results are here, https://github.com/CICE-Consortium/Test-Results/wiki/cice_by_hash_forks#db254c11ba0a96b10f875a2d2003ec6aa9298073.

**Comment by eclare108213** [comment]
Looks good.  Please merge when you're ready.

**Pull request merged**
