### PR TITLE
deprecate upwind advection

### PR DESCRIPTION
**Pull request by eclare108213**
## PR checklist
- [x] Short (1 sentence) summary of your PR: 
First phase of code deprecation for upwind advection, following https://github.com/CICE-Consortium/CICE/wiki/Deprecated-Code-Features 
- [x] Developer(s): 
    E. Hunke
- [x] Suggest PR reviewers from list in the column to the right.
- [x] Please copy the PR test results link or provide a summary of testing completed below.

https://github.com/CICE-Consortium/Test-Results/wiki/eb77517470.badger.intel.20-08-21.210840.0

> 243 measured results of 243 total results
> 237 of 243 tests PASSED
> 0 of 243 tests PENDING
> 0 of 243 tests MISSING data
> 6 of 243 tests FAILED
> 
> [eclare@ba-fe1 testsuite.dep3]$ results.csh | grep FAIL
> FAIL badger_intel_restart_gx1_40x4_droundrobin_medium run 
> FAIL badger_intel_restart_gx1_40x4_droundrobin_medium test 
> FAIL badger_intel_restart_tx1_40x4_dsectrobin_medium run
> FAIL badger_intel_restart_tx1_40x4_dsectrobin_medium test 
> FAIL badger_intel_restart_gx3_4x4_alt04 compare bs_20200821 8.37 2.23 6.37 different-data
> FAIL badger_intel_smoke_gx3_4x4_alt04_debug_short compare bs_20200821 11.05 4.94 3.18 different-data

Four failures are the usual 40-processor fails on badger, the other two are because the alt04 test changed to use remap instead of upwind.

- How much do the PR code changes differ from the unmodified code? 
    - [x] bit for bit
    - [ ] different at roundoff level
    - [x] more substantial 
This question is harder to answer because we are removing a capability.  In that sense, answer changes are indeed substantial, but this does not change the answers for the rest of the code.
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [x] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [x] No, but alt04 changes.
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [x] Yes
    - [ ] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [ ] No 
- [x] Please provide any additional information or relevant details below:

Commented out most of the upwind related code, flagging it with ``!deprecate upwind`` to make it easier to find and remove later.  Changed subroutine names that aren’t completely commented out by adding the suffix ``_deprecated``, to catch instances where they might be called from elsewhere in the code. 

Changed the advection parameterization in alt04 to ``remap``.  This changes the answers for that test only, as expected.

Updated readthedocs documentation to its final version, since commenting out rst with identifying flags doesn’t appear to be obvious for later removal during the final deprecation stage.  If we need to reinstate the deprecated code instead of removing it completely, we can resurrect the documentation from earlier versions.

I'd like feedback on whether this process is the way we want to continue deprecating code, or if there are better ways than what's done here.

### CODE REVIEW

**Comment by eclare108213** [comment]
If upwind were used in any run (coupled or not) that executes the input_data subroutine, the code should abort because it now only allows 'remap' and 'none' as options for advection.  However I added an additional error message if advection='upwind', to warn that it has been deprecated.  If a coupled code does not execute input_data and doesn't update its own interface appropriately for the deprecation changes, then the code would probably fail to compile because the upwind subroutines are not available.  This is part of the reason for doing this in two stages, in case a user group is using those subroutines and would prefer that we not deprecate them but wasn't aware of it - this way we can reinstate them fairly easily.

I ran a test using advection='upwind', to make sure it did abort, and here's the output:

>  (abort_ice)ABORTED: 
>  (abort_ice) called from ice_init.F90
>  (abort_ice) line number         1640
>  (abort_ice) error = (input_data) ABORTING on input ERRORS
> (input_data) ERROR: abort_list = :3

It did not print the full error message, either the original one or the 'upwind deprecated' message that I just added. 
@apcraig is this what's expected from the warning system now?  Here is the code block from ice_init.F90:

```
!deprecate upwind      if (advection /= 'remap' .and. advection /= 'upwind' .and. advection /= 'none') then                       
      if (advection /= 'remap' .and. advection /= 'none') then
         if (trim(advection) == 'upwind') then
            if (my_task == master_task) write(nu_diag,*) subname//' ERROR: upwind advection has been deprecated'
         endif
         if (my_task == master_task) write(nu_diag,*) subname//' ERROR: invalid advection=',trim(advection)
         abort_list = trim(abort_list)//":3"
      endif


```

**Comment by apcraig** [comment]
There must be some additional error messages before the "ABORTED:" line?

**Comment by eclare108213** [comment]
Yes!  All the way at the top of the file - sorry I just skipped to the end to make sure it aborted.  There's a lot of other diagnostic stuff in between the warning lines 
```
(input_data) ERROR: upwind advection has been deprecated
(input_data) ERROR: invalid advection=upwind
```

and the abort message.

**Comment by apcraig** [comment]
Good.  So what's happening is that the input_data routine is trapping errors but not aborting until the end of the routine.  That way, you can see all the errors rather than having to run multiple times to trap all the errors.  The "abort_list" indicates which errors were triggered.  In this case it was just "3".  There are about 30 right now if I remember.  When an error is trapped, the error message is written out and then other diagnostic messages can be written in between before the ABORT message.  Maybe I should fix this so each error trap produces an error message that can also be written when the run is stopped.  That's probably a valuable feature to have, but is a separate issue from this.

**Comment by apcraig** [comment]
In preparation for the next release, I will merge this tomorrow morning unless any other concerns are expressed before then.  Thanks.

**Comment by eclare108213** [comment]
@apcraig 
@JFLemieux73 has requested that we keep upwind in the code, which is fine with me as long as we make sure users don't expect the tracers to work (see #267).  So far this PR only commented things out.  Here's a git question:  it's possible to revert a PR, but it looks like this will happen directly in master rather than on a fork/branch, which would break our workflow.  Is there an elegant way to do this, or should we revert the changes by hand?

**Comment by phil-blain** [comment]
@eclare108213 about reverting: you seem to be talking about the "Revert" button on GitHub. From my account, the hover text for this button on this here PR shows "Create a new pull request to revert these changes". Maybe because you have write access to the repo this option is not the same for you and in your case it would directly revert on master. 

In any case, anybody can create a local branch, use ` git revert 164fcfc` and open a PR for that branch, following our normal workflow.

**Comment by eclare108213** [comment]
Thanks @phil-blain, that's what I was wondering.  I looked at the online documentation for git revert, which wasn't clear.

**Comment by apcraig** [comment]
@eclare108213, do you want me to create a PR to undo #508 and also add a check as noted in #267 on ntrcr?

**Comment by apcraig** [comment]
I'll take care of the PR to revert this.  Lets move discussion to #267

**Pull request merged**
