### PR TITLE
icepack: optionally compute 'dragio' using under-ice roughness length

### PR DESCRIPTION
**Pull request by phil-blain**
## PR checklist
- [x] Short (1 sentence) summary of your PR: 
    See title.
- [X] Developer(s): 
    P Blain.
- [X] Suggest PR reviewers from list in the column to the right.
- [x] Please copy the PR test results link or provide a summary of testing completed below.
    I'm running the base_suite now and will update with the results.
- How much do the PR code changes differ from the unmodified code? 
    - [X] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [x] Yes, https://github.com/CICE-Consortium/Icepack/pull/366, which was [just merged](https://github.com/CICE-Consortium/Icepack/pull/366#event-4923605865).
    - [ ] No
- Does this PR add any new test cases?
    - [x] Yes
    - [ ] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [x] Yes
    - [ ] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [ ] No 
- [x] Please provide any additional information or relevant details below:

- The first commit just updates Icepack to the latest version, adds `calc_dragio` and `iceruf_ocn` to the CICE namelist and adds a test with ̀calc_dragio=T`. I added both variables to the index in the doc and I felt that was enough in terms of documentaiton; the Roy et al 2015 paper is already referenced in the Icepack doc.
- The second commit is not absolutely necessary, but I think that it's more consistent to use the 1st ocean level thickness if we have access to it internally, so that's why I added that change.

### CODE REVIEW

**Comment by phil-blain** [comment]
cc @JFLemieux73

**Review by eclare108213 — APPROVED** [review]

**Review by apcraig — APPROVED** [review]

**Comment by apcraig** [comment]
I think this is ready to merge?

@phil-blain, I assume this is pointing to a804 in icepack, current head of Icepack master in CICE-Consortium?  Is there anyway to tell that in the PR?  How do we know it's pointing to something on the CICE-Consortium master versus something on a branch in another fork?

**Comment by phil-blain** [comment]
Yes, it is ready to merge, if you feel we don't need to wait for the base_suite results. I will add them today. We can wait for the tests.

Re Icepack, if you go to the "Files changed" tab of the PR,  scroll to the bottom where Icepack is listed, and click on the "9 files" link, you see that the URL of the "Comparing changes" pages that this links to ends with `37f2a17b97a5314c2c76c7ccd30b9bada9653bd0...a80472b547aa6d7a85f8ae5e1449273a323e0371`, so that means Icepack is changed from CICE-Consortium/Icepack@37f2a17b97a5314c2c76c7ccd30b9bada9653bd0 to  CICE-Consortium/Icepack@a80472b547aa6d7a85f8ae5e1449273a323e0371, which is indeed the tip of Icepack's `master` at the moment.

One way to check on  GtiHub if the Icepack commit this PR points to is indeed merged to the Consortium's Icepack `master` branch is to follow the link to the commit page: CICE-Consortium/Icepack@a80472b547aa6d7a85f8ae5e1449273a323e0371. At the bottom of the box with the commit message you can see "**master** (#366)" which means that this commit entered the history of the `master` branch when PR CICE-Consortium/Icepack#366 was merged.

**Comment by phil-blain** [comment]
Thanks @apcraig. The test results are as expected:

~~~bash
322 measured results of 322 total results
320 of 322 tests PASSED
0 of 322 tests PENDING
2 of 322 tests MISSING data
0 of 322 tests FAILED
$ ./results.csh | \grep MISS
MISS daley_intel_smoke_gx3_4x1_calcdragio complog ff88891 missing-data
MISS daley_intel_smoke_gx3_4x1_calcdragio compare ff88891  -1 -1 -1 missing-data
~~~

The missing data is for the test I'm adding in this PR. I've updated the PR description with this info.

**Pull request merged**
