### PR TITLE
Revp v5

### PR DESCRIPTION
**Pull request by TillRasmussen**
See description of #226. Test has been made and results are similar
New pull request due to multiple changes in the code within the last week or so.

### CODE REVIEW

**Comment by TillRasmussen** [comment]
Suggested reviewer @JFLemieux73 @apcraig

**Comment by apcraig** [comment]
Thanks for cleaning up the PR, sorry to have to go thru that again.  I find that doing a "git pull --rebase" when updating a branch to master tends to help avoid these redundant code issues.  Resolving the conflicts is slightly different in that case, and you have to work thru the git pull until all conflicts are resolved, but it then provides a clean set of changes on top of the current master.

**Comment by apcraig** [comment]
@TillRasmussen @JFLemieux73 @eclare108213 
Let me know if this has been validated and is ready to merge.  I can do it.  Or @eclare108213, feel free to merge if it's ready.

**Comment by eclare108213** [comment]
This looks okay to me.  I'd like @JFLemieux73 to look at it too.  I'd like the commented out lines to stay for now, so that they are in the repository as such, and we can delete them later.  I think I asked this before and it was probably answered -- was the documentation updated to match these changes?  (Sorry it's easier to ask than to go looking for it, but this way also we get the answer in the PR itself.)

**Comment by eclare108213** [comment]
@JFLemieux73 said he would update the documentation in #226 comments.  I think that's what he added in #236 --  I want to make sure.

**Comment by JFLemieux73** [comment]
Yes I have updated the documentation for the revised EVP.  This was mostly done in #229.

**Comment by JFLemieux73** [comment]
I am doing some test before approving the PR. I just tested the standard EVP in revp v5 with the standard EVP in the current master. I ran both for 1 day and just looked at hice. It is not BFB (max diff of 0.0009 m). Is it due to the modifs made by Till in ice_dyn_evp or something else changed in the code since Till created the branch? Any ideas?

**Comment by TillRasmussen** [comment]
I think that it can result in small differences. I will try to calculate the constants as it is done in the new and the old version and subtract these.

**Comment by eclare108213** [comment]
Thanks @JFLemieux73
This is great. To satisfy my curiosity, I would like to see more comparisons e.g. between revp in v5 and v6, but we do not need to do that in the next week.  If it’s easy and you have time, please run the QC, for the record.  My opinion is that it’s not necessary but would be nice to have, for completeness — I consider the v5 version buggy so the outcome of the QC doesn’t matter for our decision whether to accept the changes. We can merge this PR any time now.

Sent with BlackBerry Work
(www.blackberry.com)

**Comment by TillRasmussen** [comment]
I have subtracted the output of the velocities after the first time step. This has been made as a binary dump of uvel and vvel just after the evp routine.
The difference is
>>> np.min(newout-oldout)
-1.1945197435359045e-15
>>> np.max(newout-oldout)
1.3592507111179208e-15
This would be some sort of roundoff errors.

**Pull request merged**
