### PR TITLE
CICE: Floe size distribution 

### PR DESCRIPTION
**Pull request by eclare108213**
PR checklist
- [x] Short (1 sentence) summary of your PR: 
Changes to CICE driver to implement floe size distribution in Icepack.
- [x] Developer(s): 
Lettie Roach, Elizabeth Hunke
- [x] Suggest PR reviewers from list in the column to the right.
- [ ] Please copy the PR test results link or provide a summary of testing completed below.
Passes basic tests; currently undergoing more extensive testing
- How much do the PR code changes differ from the unmodified code? 
    - [ ] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [x] Yes
    - [ ] No
- Does this PR add any new test cases?
    - [x] Yes
    - [ ] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [x] Yes
    - [ ] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [ ] No 
- [x] Please provide any additional information or relevant details below:

This PR is not yet ready to merge, pending 
- [ ] move ww3 forcing file from cicecore to ftp
- [x] add abort if fsd and bgc are both on (like Icepack driver)
- [ ] additions to PIO history and restart modules.  
- [ ] execute full test suites
- [ ] run all tests with -fsd12 to see what breaks
- [x] perform a longer run with fsd12 and ww3 forcing and check the output for plausibility
- [x] Revert Icepack here to the master version and update it after the [Icepack PR](https://github.com/CICE-Consortium/Icepack/pull/281) is merged
- [x] Review documentation for completeness and consistency with Icepack's
- [x] Compare CICE and Icepack driver changes to see if they are consistent and we didn't miss something
- [x] merge [Icepack PR](https://github.com/CICE-Consortium/Icepack/pull/281)

See also [FSD project board](https://github.com/CICE-Consortium/CICE/projects/3)

### CODE REVIEW

**Comment by apcraig** [comment]
Testing results look good.  See hash 3b487bde1bd12 at https://github.com/CICE-Consortium/Test-Results/wiki/cice_by_hash_forks.  The failure on gordon is missing ww3 dataset.  I have manually moved that file onto gordon and when I retested, that passed.  Comparison failures on gordon are for fsd tests that don't have baselines yet.  On izumi, there are more failures, but most are larger jobs and medium runs.  Over the last several days, izumi has been choking on these jobs, not just with this version but others that I've been testing.  Otherwise, there are no failures on izumi that are not expected.

I think this can be merged after the fsd Icepack merge is complete and the icepack version is updated on this branch.  Once that happens, we should do some quick retesting to confirm everything is still working and then merge.

**Comment by apcraig** [comment]
I am running full test suites on gordon and izumi on the current PR including the latest icepack master (that includes the icepack fsd PR).

**Comment by eclare108213** [comment]
I was about to check in some last-minute changes -- some of the FSD arrays do not appear to be initialized, but I'm not sure if it's a problem:  they are probably initialized when tr_fsd=T but not when tr_fsd=F, even though they are allocated.  This seems risky and inefficient to me.

**Comment by apcraig** [comment]
@eclare108213, Feel free to make some final changes.  I can retest.  I think it's good to fix those simple known issues now when we're thinking about it.  I will just let these suites run.  Let me know when you feel it's "final" and I'll retest.  I won't merger anything until I've confirmed with you that it's ready to go.

**Comment by apcraig** [comment]
Testing with the current version on izumi and gordon looks good.  See hash 829e4b85f8 at https://github.com/CICE-Consortium/Test-Results/wiki/cice_by_hash_forks.  I will retest when final changes are complete.

**Comment by eclare108213** [comment]
I'm having several problems with the wave forcing file, efreq ww3.20100101_efreq_remapgx3.nc.
In particular, ferret aborts:

> yes? use ww3.20100101_efreq_remapgx3.nc 
>  *** NOTE: Units on axis "f" are not recognized: s-1
>  *** NOTE: They will not be convertible:
>  *** NOTE:
> At line 1981 of file nc_get_attrib.f
> Fortran runtime error: End of record

Would it work to change the units to 1/s ?
Also I think we should change f=25 to nf=25 in the file, so that f doesn't refer to two different things.

A potentially more serious problem:  There are 1.e36 values in ocean grid cells, mainly along land margins.  For now, we can just set these to zero in the code, but this file needs to be cleaned up.  (We also do not have an equivalent forcing file for gx1, which should probably be dealt with gracefully, somehow.)

Opinions about whether to fix these issues now or later?

**Comment by apcraig** [comment]
I think we should fix the file and implementation now.  We haven't even dropped the file onto ftp, so it's still a good time.  I propose we create a slight different filename for the new file.  I can probably quickly modify the file with nco, let me know if you want me to do that.

**Comment by eclare108213** [comment]
@lettie-roach just said she can work on FSD tasks tomorrow, including this file.  The quick mods could be done with NCO, but I'm more concerned about the  location of the 1.e36 values, which we are discussing.

**Comment by eclare108213** [comment]
I have a test in the queue for the history change, but for some reason my runs aren't finishing due to dropped compute nodes, most likely a problem with the computer, not the code.  So that commit still needs to be looked at closely.

**Comment by eclare108213** [comment]
This is the to-do list from the top of this PR, with requests.  Let me know if there are issues or how I can help.

@duvivier, can you do these items (hopefully today)?
- [ ] move ww3 forcing file from cicecore to ftp (change filename if needed)
- [ ] Review documentation for completeness and consistency with Icepack's

@eclare108213:
- [ ] Revert Icepack here to the master version 
- [ ] Compare CICE and Icepack driver changes to see if they are consistent and we didn't miss something
- [ ] Review documentation for completeness and consistency with Icepack's

@lettie-roach:
- [ ] perform a longer run with -s fsd12ww3 and check the output for plausibility

@apcraig:
- [ ] merge [Icepack PR](https://github.com/CICE-Consortium/Icepack/pull/281)
- [ ] execute full test suites
- [ ] run all tests with -fsd12 to see if anything breaks other than BGC

**Comment by apcraig** [comment]
In terms of getting this PR finalized and testing done, we need to

- finish icepack fsd changes, test, merge icepack PR
- update icepack version for this PR
- test cice with newest cice

I can start some of this now, but a big step is to merge the icepack PR.  I don't want to merge that prematurely if work is still ongoing.  @eclare108213, @lettie-roach, can you let me know when the icepack PR, https://github.com/CICE-Consortium/Icepack/pull/286, is done changing and could undergo final testing which would then lead to the Icepack PR being merged.

**Comment by eclare108213** [comment]
Yes.  I am comparing the drivers now and finding a few things to clean up, nothing that affects the calculations so far.  I'll let you know when I'm done.

**Comment by eclare108213** [comment]
We haven't yet copied all the changes to CICE_InitMod.F90 and CICE_RunMod.F90 to all the other drivers.  There are 4 of them!  How important is that?  Probably should do it...

**Comment by apcraig** [comment]
We should update the other CICE drivers.  I can do that when I update Icepack in the CICE fsd PR if you like.

**Comment by eclare108213** [comment]
I tried to change the icepack in @lettie-roach's fork (this branch) to the consortium version, including following the 'completely remove and replace icepack' instructions from the git workflow, and it's still showing up a differences in the list of changed files.  So I don't know how to do this... @apcraig (or @phil-blain) please help me figure this out, and yes it would be fantastic if you'd also update the drivers.  I'll work on the lists of recent changes, for the release.  Thx.

**Comment by eclare108213** [comment]
Woo hoo, I figured it out, following instructions in #377 for the master branch, and then checked out the fsd1 branch and committed icepack again.   Seems to have worked...

**Comment by eclare108213** [comment]
And the merge fails because it has the older Icepack version, which will be fixed when the new PR is merged and updated in CICE.

**Comment by apcraig** [comment]
Right, reverting back to the current Icepack version in CICE is not what we wanted.  When we committed the ifsd1 PR to the Icepack, I pushed an update to @lettie-roach fsd branch to point to that.  We'll need to do that again once we push ifsdech branch to the Consortium.  The fact it's failing now is OK, I'll update Icepack again when we push the next PR.

**Comment by eclare108213** [comment]
Okay, I'll try to stay out of the way!

**Comment by eclare108213** [comment]
Except for moving the ww3 file to ftp and final testing, this PR looks ready to merge.

**Comment by apcraig** [comment]
I think this is ready to merge.  The testing looks good.  https://github.com/CICE-Consortium/Test-Results/wiki/cice_by_hash_forks hash a7080a4a30.  I will merge this now.

**Comment by daveh150** [comment]
Hi Everyone,

 

In regard to the FSD, I am running into an issue where in ice_in, if I specify 

 

tr_fsd = .false., 

nfsd = 0 

 

The run stopps with error trying to define history file ‘nf’ as an unlimited dimension:

 

(abort_ice)ABORTED:

(abort_ice) error = (ice_write_hist)ERROR: defining dim nf

(abort_ice)NetCDF: NC_UNLIMITED size already in use

 

 

The issue is in ice_history_write.F90: line 193, where fsd is defined without a check if tr_fsd is defined.

 

Question: Should we put a check if tr_fsd = .true. before defining ‘nf’ as a dimension? OR is this handled differently in other tracers? I can make that change and submit a pull request if needed.  

 

Thanks for the help and advice!

David 

 

 

David A. Hebert

Ocean Sciences Division, Code 7322 
Naval Research Laboratory 
Stennis Space Center, MS 39529
(228)688-5846; DSN 828-5846 
http://www.nrl.navy.mil <http://www.nrl.navy.mil/>

**Comment by eclare108213** [comment]
If you are running with any ice at all, you ought to have at least one floe size category!  I would think that nf=1 should be the default when tr_fsd=F, but maybe it's not.

**Comment by duvivier** [comment]
Maybe this is a documentation item. We should put in there that nf must be .ge. 1. @duvivier - do this asap!

**Comment by daveh150** [comment]
Physically, that makes sense. 

 

Code wise, when tr_fsd = .false., is there any output that will have ‘nf’ as a dimension? I suppose it doesn’t hurt to have a dimension that isn’t used in the history NetCDF.  Just trying to avoid extraneous definitions and see what is consistent with the other tracers when they are false.

 

Thank you,

David

 

 

David A. Hebert

Ocean Sciences Division, Code 7322 
Naval Research Laboratory 
Stennis Space Center, MS 39529
(228)688-5846; DSN 828-5846 
 <http://www.nrl.navy.mil/> http://www.nrl.navy.mil

**Comment by eclare108213** [comment]
Agreed.  If the FSD is off, then there is no need to have nf in the history output.  However it doesn't take up much space and would make it clear exactly how many floe size categories were in use.  Also, if someone's analysis software expects it to be there and breaks because it isn't, they might be a little annoyed (but that just shows lack of flexibility in their software).  I think we should make it clear in the doc that nf >= 1, as @duvivier suggests.  I'm open to others' opinions about whether nf should be included in the output when it isn't used as a netcdf dimension.

**Comment by apcraig** [comment]
I would argue if there is a clean way to turn off fsd (tr_fsd) then the value of nf should not matter and it should be fine to be zero or anything else when fsd is off.  And that (tr_fsd) should also control whether the fsd output is added to the history/restart or not.  I would argue that this is the most appropriate way to handle all optional features / output fields.  Would this be a lot of work?  I'm willing to have a look and help clean this up if it's not too complicated.  If it's challenging to fix properly, then I am fine with the strategy that nf >=0 for all cases.  We should also add a run time check to verify a valid value.  It should be more than just documentation.  That same strategy should be applied to any other optional tracer that also needs to be >=0 even if it's not turned on.

**Comment by eclare108213** [comment]
It is fine with me for tr_fsd to control whether nf is added to the history/restart files.  @apcraig I accept your offer to take a look and clean it up if it's straightforward!  Thanks.  However I do think that the default value should be nf=1 when FSD is off, regardless of whether it's written to the files, because that is the physically meaningful value.  It's possible that some other parameterization will need/want to use it in the future.

**Pull request merged**
