### PR TITLE
use cell-centered ice velocity for high-freq wind stress calculation

### PR DESCRIPTION
**Pull request by eclare108213**
- [x] Short (1 sentence) summary of your PR: 
Use interpolated, T-grid cell-centered ice velocity for high-frequency wind stress calculation instead of U-grid velocity
- [x] Developer(s): 
E. Hunke, based on modification to MPAS-seaice
- [x] Suggest PR reviewers from list in the column to the right.
- [ ] Please copy the PR test results link or provide a summary of testing completed below.
     https://github.com/CICE-Consortium/Test-Results/wiki/5a0a559aaf.badger.intel.21-03-13.231354.0
    40-pe runs always fail on badger.
- How much do the PR code changes differ from the unmodified code? 
    - [x] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [x] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [x] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [ ] Yes
    - [x] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [x] No but the cell-centered assumption could be noted there
- [x] Please provide any additional information or relevant details below:
Addresses https://github.com/CICE-Consortium/CICE/issues/544.
This PR should change the answers for -s alt01 tests, because it alters the ice velocity used to calculate the wind stress when highfreq=T.  However the ice dynamics is turned off for alt01 (kdyn=0), so the ice velocity is identically zero and the results are BFB.  We need to fix the alt01 test.

### CODE REVIEW

**Comment by eclare108213** [comment]
We need to fix the test combinations so that kdyn is on when highfreq is on.  alt01 has kdyn=0 (off), as does boxdyn.  I think we could just change alt01 to have kdyn=1.

**Comment by apcraig** [comment]
@eclare108213, would you like to update the alt01 test as part of this PR or do you prefer that be a separate PR?

**Comment by eclare108213** [comment]
There's potentially a bigger problem with the alt01 and boxdyn tests which I need to look at more closely (why is kdyn =0 off for a 'dyn' box test?).  If the other PR reviewers approve this PR as it is, then I think we should go ahead and merge it and keep moving forward.  If I manage to look at the tests before then and see how to change them, then I might add that to this PR, but it's not necessary in my opinion.

**Review by proteanplanet — APPROVED** [review]
Approved upon visual inspection. One point to note is the problem of diffusive dynamic coupling through scalar grid points.  That cannot be addressed in this PR which is a fix to an existing problem.

**Review by mattdturner — APPROVED** [review]
Approved via visual inspection

**Comment by eclare108213** [comment]
I changed the alt01 test to turn dynamics on, in order to test the effects of changes in the highfreq calculation.  As expected, they aren't BFB.  Results of just the revised alt01 comparisons, with and without this code modification are here:
https://github.com/CICE-Consortium/Test-Results/wiki/7ba26347b2.badger.intel.21-03-15.174352.0
I don't think we need to do QC on this, but we can if anyone thinks we should.
(The boxdyn test, which also has kdyn=0, is poorly named, something we can change in a different PR.  I'll note this in an issue somewhere...)

**Review by apcraig — APPROVED** [review]

**Pull request merged**
