### PR TITLE
Update Icepack tracer calls for recent refactor

### PR DESCRIPTION
**Pull request by apcraig**
## PR checklist
- [X] Short (1 sentence) summary of your PR: 
    Update Icepack tracer calls due to recent refactor
- [X] Developer(s): 
    apcraig, eclare
- [X] Suggest PR reviewers from list in the column to the right.
- [ ] Please copy the PR test results link or provide a summary of testing completed below.
    TBD 
- How much do the PR code changes differ from the unmodified code? 
    - [X] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [X] Yes
    - [ ] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [X] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [ ] Yes
    - [X] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [X] No 
- [ ] Please provide any additional information or relevant details below:

### CODE REVIEW

**Comment by eclare108213** [comment]
Let me know when you get this to compile and I will also run a test suite on badger.  What version (or hash) are you doing regressions against?

**Comment by eclare108213** [comment]
In the icepack section of the developer guide, please change this sentence from 

> It does not directly “use” Icepack data and access Icepack data only thru interfaces.

to 

> It does not directly “use” Icepack data, accessing Icepack data only through interfaces.

**Comment by apcraig** [comment]
This version won't work until the Icepack PR is merged.  You should be able to build a sandbox manually from this branch plus the v12a branch of Icepack off my fork.  I have been comparing against CICE hash 38816bac934 as that was a master version for a couple weeks until recently.

**Comment by apcraig** [comment]
I updated the documentation as suggested.

**Pull request merged**
