### PR TITLE
machine files for cesium: added debug options

### PR DESCRIPTION
**Pull request by phil-blain**
Changes to my machine files

- Developer(s):Philippe Blain

- Please suggest code Pull Request reviewers in the column at right. 

- Are the code changes bit for bit, different at roundoff level, or more substantial? BFB

- Please include the link to test results or paste the summary block from the bottom of the testing output below.

- Does this PR create or have dependencies on Icepack or any other models? No

- Is the documentation being updated with this PR? (Y/N) N
If not, does the documentation need to be updated separately at a later time? (Y/N) N

Note: "Documentation" includes information on the wiki and .rst files in doc/source/, 
which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/.

- Other Relevant Details:

### CODE REVIEW

**Comment by eclare108213** [comment]
@apcraig @dabail10 @duvivier 
The travis tests are failing, apparently because of ftp data from NCAR:

> The command "wget ftp://ftp.cgd.ucar.edu/archive/Model-Data/CICE/CICE_data_forcing_gx3_all.tar.gz && tar xvfz CICE_data_forcing_gx3_all.tar.gz -C ~" failed and exited with 4 during .

Could one of you look into that, please?
Thx

**Comment by apcraig** [comment]
I retriggered the travis test and it seems to be working.  Will merge when travis passes.

**Comment by duvivier** [comment]
I just checked. The files are there... Nothing has changed in the directories since November. I haven't had any notification that the systems are down. Are any other tests failing elsewhere?

**Comment by eclare108213** [comment]
I thought I'd seen a similar failure a week or so ago, but I'm not finding it now so it must have sorted itself out.  Let's just keep an eye on it.

**Pull request merged**
