### PR TITLE
Update timeseries plots to resolve issue with some fields

### PR DESCRIPTION
**Pull request by mattdturner**
## PR checklist
- [X] Short (1 sentence) summary of your PR: 
    Update the 2 timeseries plotting scripts to accurately extract the data from log files.  
- [X] Developer(s): 
    @mattdturner 
- [ ] Suggest PR reviewers from list in the column to the right.
- [X] Please copy the PR test results link or provide a summary of testing completed below.
    N/A.  This only touches the plotting scripts, not the model code.
- How much do the PR code changes differ from the unmodified code? 
    - [X] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [X] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [X] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [ ] Yes
    - [X] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [X] No 
- [X] Please provide any additional information or relevant details below:

1. Update the 2 timeseries plotting scripts to accurately extract the data from log files.  
2. Also add an option to plot SST from the python plotting script.  
3. This addresses issue #538

### CODE REVIEW

**Comment by mattdturner** [comment]
@eclare108213 This should address the plotting issues you were having in #538 .  I will need to create a separate PR to allow users to pass variable names as arguments, once I figure out a good way to implement it.

**Review by eclare108213 — APPROVED** [review]
There are two typos in timeseries.csh - this is a good time to fix them:

1. change Manuallyl to Manually
2. change alis to axis

Otherwise this works for me!  thanks much.

**Review by eclare108213 — COMMENTED** [review]
@mattdturner  - one more thought -
To not change the functionality too much at this point, it would be better to not include the sst and arwt tot mass in the timeseries list, for this merge.   They can be included for plotting once you've figured out a more general implementation (which isn't a super high priority).  Sound okay?

**Comment by eclare108213** [comment]
Thank you @mattdturner !  I'll merge this when the checks finish.

**Comment by mattdturner** [comment]
@eclare108213 That sounds good to me.  I went ahead and removed those variables from the list and pushed a new commit.

**Pull request merged**
