### PR TITLE
Deprecate zsalinity

### PR DESCRIPTION
**Pull request by apcraig**
## PR checklist
- [X] Short (1 sentence) summary of your PR: 
    Deprecate zsalinity
- [X] Developer(s): 
    apcraig
- [X] Suggest PR reviewers from list in the column to the right.
- [X] Please copy the PR test results link or provide a summary of testing completed below.
    Bit-for-bit full test suite on cheyenne, https://github.com/CICE-Consortium/Test-Results/wiki/cice_by_hash_forks#f836c7d5b39f7c3dc272ab50f6db615341110343
- How much do the PR code changes differ from the unmodified code? 
    - [X] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [X] Yes
    - [ ] No
- Does this PR update the Icepack submodule?  If so, the Icepack submodule must point to a hash on Icepack's main branch.
    - [X] Yes
    - [ ] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [X] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [X] Yes
    - [ ] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [ ] No 
- [ ] Please provide any additional information or relevant details below:

### CODE REVIEW

**Comment by apcraig** [comment]
I still need to update this PR with https://github.com/CICE-Consortium/Icepack/pull/448 once that PR is merged.  But these changes can be reviewed for now.

**Comment by apcraig** [comment]
I rebased this after the snow mods, all testing passed.  Will need to update Icepack before this PR is ready, see https://github.com/CICE-Consortium/Icepack/pull/448.

**Review by eclare108213 — APPROVED** [review]
Approving pending final testing with merged version of Icepack https://github.com/CICE-Consortium/Icepack/pull/448.

**Comment by apcraig** [comment]
I have updated Icepack and am doing some final testing.  Once the offline testing and Github Actions completes, I will merge unless I hear otherwise.

**Comment by apcraig** [comment]
Testing and github actions all pass.  Merging.

**Pull request merged**
