### PR TITLE
Read HYCOM fields + other minor corrections

### PR DESCRIPTION
**Pull request by mhrib**
1) Subroutines for reading HYCOM initial SST+SSS forcing and HYCOM like NetCDF atmospheric forcing

2) Minor corrections in popgrid_nc in ice_grid.F90: All records are the first - unlike for binary file formats

3) Minor changes to "read_basalstress_bathy" in ice.grid.F90 and by default called, if "bathymetry.nc" file exists.

--o--

- Developer(s): Mads Hvid Ribergaard, DMI

- Please suggest code Pull Request reviewers in the column at right.

- Are the code changes bit for bit, different at roundoff level, or more substantial?
Yes, BFB

- Please include the link to test results or paste the summary block from the bottom of the testing output below.

- Does this PR create or have dependencies on Icepack or any other models? 

- Is the documentation being updated with this PR? (Y/N) N
If not, does the documentation need to be updated separately at a later time? (Y/N) Don't think so.

Note: "Documentation" includes information on the wiki and .rst files in doc/source/, 
which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/.

- Other Relevant Details:

ad 1) HYCOM forcing:
Do not conflict with other stuff. But nice to have for DMI :-)

ad 2) "popgrid_nc" record-numbers in ice_grid.F90
Corrected all nrec to 1, as it is the first record that is needed for each variables: htn, hte, kmt, etc.
There is ONLY one record for each variable! This is different from "popgrid"-binary, which consists of 7 variables - ie. need a specific record number.

ad 3) read_basalstress_bathy:
This is a suggestion made in parallel to PR #222 by dabail22, which I was not aware of. Perhaps useful to merge, perhaps not... 

--o--

I think by this PR, the #160 can be deleted. Its content is included within:
1) #205 : EVP kernel vectorized.
1a) #205 OMP issues. Indication of where to look. Some of them has already been changed / comment out.
2) #219 : revised EVP.
3) Splitting namelist. I do not think this is relevant anymore, after the reading has been re-structured into one single file.
4) #224 DMI (HYCOM) specific: This one:-)
5) #195 : Allocatable dynamics (Implemented)

### CODE REVIEW

**Comment by apcraig** [comment]
I suspect the bathy mods will conflict with #222, and with #222 going in, we may not want bathy mods here.  Also, do we need to update the documentation to describe the new hycom forcing option?

**Comment by dabail10** [comment]
Do you want me to withdraw the PR and resolve the conflicts with this later?

**Comment by apcraig** [comment]
@dabail10, this PR is lower priority than #222.  I think we want to get #222 merged then we can decide what to do with the bathy changes in this PR.  I suspect we'll just remove them from this PR, but we can decide later.

**Comment by mhrib** [comment]
@dabail10 and @apcraig : I have made a new PR ( https://github.com/CICE-Consortium/CICE/pull/230 ), without the basalstress_bathy stuff. It is/was almost redundant and I was just not aware of PR #222 when I made the PR #224


@apcraig : Also added documentation to the new PR (#230), which replaces #224 ... and which is up-to-date with master.

rgs
Mads



________________________________________

**Comment by mhrib** [comment]
Replaced by PR #230

**Pull request closed without merging**
