### PR TITLE
Ctest timings

### PR DESCRIPTION
**Pull request by mattdturner**
Add timing information to the CDash online dashboard
Developer(s): Matt Turner
Updated documentation (Y/N): N
Results (bit for bit, roundoff, climate changing): N/A
Code review: 
Other Relevant Details:

- Timing information is posted for every *_run* test

### CODE REVIEW

**Comment by mattdturner** [comment]
This PR addresses Issue 49 (https://github.com/CICE-Consortium/CICE/issues/49)

**Comment by eclare108213** [comment]
http://my.cdash.org/viewTest.php?buildid=1340131
I managed to run this branch and upload the results!  I had changed the proxy settings for downloading python packages, and that also fixed this problem.  The results are not stellar because I told run.suite to compare with a baseline that does not exist (oops).   I suggest that if a user makes this particular mistake, that the results not be uploaded to CDash.  Also, CDash is not showing the timings because my test runs create.case and the other scripts from the repo, which do not yet have the commands to be merged in this PR.

**Comment by eclare108213** [comment]
Matt, I wasn't very clear in my last comment.  Is it possible to have the scripts not upload results to CDash when the error is that a baseline doesn't exist?  That's a user problem, not a code problem.

**Comment by mattdturner** [comment]
@eclare108213 Do you want it to not upload anything to CDash if the baseline for a test doesn't exist?  Or not upload data for the specific tests that do not have a baseline?  (The former would be easier to implement)

**Comment by eclare108213** [comment]
The former!  Just write a message saying nothing will be uploaded because the baseline doesn’t exist, but the results can be looked at locally [where].  Thanks!

**Pull request merged**
