### PR TITLE
fsd2

### PR DESCRIPTION
**Pull request by lettie-roach**
## PR checklist
- [x] Short (1 sentence) summary of your PR: 
    Correction to 'wave_spec_type' logic
- [x] Developer(s): 
    @lettie-roach 
- [x] Suggest PR reviewers from list in the column to the right.
@eclare108213 @apcraig @duvivier 
- [x] Please copy the PR test results link or provide a summary of testing completed below.

https://github.com/CICE-Consortium/Test-Results/wiki/c52a091233.badger.intel.20-01-24.033842

225 of 236 tests PASSED
10 of 236 tests FAILED
0 of 236 tests PENDING

See explanation below (@eclare108213).

- How much do the PR code changes differ from the unmodified code? 
    - [ ] bit for bit
    - [ ] different at roundoff level
    - [x] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [x] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [x] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [x] Yes
    - [ ] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [ ] No 
- [x] Please provide any additional information or relevant details below:

Correction to 'wave_spec_type' - remove 'file' option (redundant). Updated documentation. 

```
wave_spec_type
none = no wave data provided, no wave-ice interactions
profile = use a hard-coded, default profile for testing wave-ice interactions
constant = wave data file is provided, use constant wave spectrum, for testing
random = wave data file is provided, wave spectrum generated using random number
```
I also changed the code so that if wave_spec_type = 'none', then the wave spectrum is set to zero. Previously, we used a dummy fixed wave spectrum in this case, which was useful for code testing, but I think should be zeroed out for the general user.

The FSD physics is unchanged, but the logic for the wave forcing has been corrected, which changes the answers for the fsd12 test option.  @eclare108213 changed the fsd12 test because it was aborting due to the new wave_spec_type logic.

### CODE REVIEW

**Comment by eclare108213** [comment]
Travis CI is failing on the ftp data retrieval.  I relaunched it and it failed again.

**Comment by lettie-roach** [comment]
Yes OK, I agree - adding the 'profile' option is a good idea.

**Comment by lettie-roach** [comment]
There shouldn't be changes to Icepack. The ones in the diff aren't mine -
maybe I'm out of sync with the master. I don't know how to run the test
suites. I don't think it will be BFB since the options are different

**Comment by eclare108213** [comment]
Okay, then you have something to learn during the tutorial!  I'll try to get a set of tests running here this week.   I'll let @apcraig figure out the Icepack thing and make a recommendation for what to do.  Thanks!

**Comment by eclare108213** [comment]
Ran the base_suite and compared with the current master.  The fsd12 (no ww3) tests fails because of the namelist change, as expected.  The ‘robin’ decomposition tests are failing for an unknown reason, but the fsd changes should not be contributing; both appear to have dropped nodes and timed out.  The JRA runs fails because the data is still unavailable.  I think these results are acceptable and the PR is ready to merge.

**Comment by eclare108213** [comment]
@apcraig please double-check that the Icepack change is desirable in this commit.  Thx

**Pull request merged**
