### PR TITLE
Revised EVP updated

### PR DESCRIPTION
**Pull request by mhrib**
Revised EVP parameters, according to Kimmirtz, Danilov and Losch, 2015

- Developer(s): Till Rasmussen and Mads Hvid Ribergaard, DMI

- Please suggest code Pull Request reviewers in the column at right.
Elisabeth?, Tony?

- Are the code changes bit for bit, different at roundoff level, or more substantial?
With *conservative* settings - AND revised_evp=.false. - it should output Bit-for-bit identical.
With revised_evp=.true. the settings has changed. Therefore obvious NOT bit-to-bit identical

- Is the documentation being updated with this PR? (Y/N) N
If not, does the documentation need to be updated separately at a later time? (Y/N) ??
Note: "Documentation" includes information on the wiki and .rst files in doc/source/, 
which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/.

- Other Relevant Details:

affected files:
./cicecore/cicedynB/dynamics/ice_dyn_evp.F90
./cicecore/cicedynB/dynamics/ice_dyn_shared.F90 (for namelist)
./cicecore/cicedynB/general/ice_init.F90 (for namelist)

Namelist (these are the default values, ONLY relevant for revised_evp=.true.):
&dynamics_nml
brlx = 300.0
arlx1i = 1.0/300.0   

NOTE: The values for "brlx and arlx1i" are overwritten in ice_dyn_shared for revised_evp=.false.

----

Have tested identical md5sum's for 24 iterations with GX3 using "revised_evp=.false.".
GNU compiler (Cray XT50) with the following FFLAGS:

FFLAGS := -g -O0 -fsignaling-nans -fno-reciprocal-math -ftrapping-math -fno-associative-math -fno-unsafe-math-optimizations

### CODE REVIEW

**Comment by apcraig** [comment]
We need to update the documentation for the new namelist.  Does any testing need to change?

**Comment by JFLemieux73** [comment]
Hi everyone,

I made more tests to understand why the revised evp does not converge while others (e.g. Kimmritz et al) claim that it does.

To be more in line with Kimmritz et al I made some tests with kstrength=0 (with Pstar) and I also increased puny from 1e-11 to 2e-9 so that it is consistent with other VP models. Whatever I tried it never converged. In fact the only test that seemed to converge was when I decreased Pstar by two orders of magnitude. 

Here is some info about my experiments (for each of these I ran the model for one day with either ndte=25000 or ndte=20000 and subtracted the two thickness fields). dhmax is the maximum (absolute) thickness difference. Note that history_avg=true. 

---------------------------
run1
kstrength=1
brlx=300,arlxi=1/brlx

dhmax=8.73e-5 m

---------------------------
run2
kstrength=0
brlx=300,arlxi=1/brlx
Pstar=2.75e4

dhmax=6.12736e-5 m

---------------------------
run3
kstrength=0
brlx=300,arlxi=1/brlx
Pstar=2.75e3

dhmax=9.5367e-7 m

---------------------------
run4
kstrength=0
brlx=300,arlxi=1/brlx
Pstar=2.75e2

dhmax=2e-10 m

---------------------------------------------------------------------
run5
kstrength=0
brlx=300,arlxi=1/brlx
Pstar=2.75e4
puny=2e-9 for tinyarea

dhmax=5.54323e-5 m

---------------------------
run6
brlx=500,arlxi=1/brlx
kstrength=0
Pstar=2.75e4
puny=2e-9 for tinyarea

dhmax=1.37568e-4 m

---------------------------
run7
brlx=700,arlxi=1/brlx
kstrength=0
Pstar=2.75e4
puny=2e-9 for tinyarea

dhmax=8.97646e-5 m

---------------------------
run8
brlx=200,arlxi=1/brlx
kstrength=0
Pstar=2.75e4
puny=2e-9 for tinyarea

dhmax= 3.07798e-4 m

---------------------------------------------------------------------
run9
brlx=300,arlxi=1/brlx
kstrength=0
Pstar=2.75e4
puny=2e-9 for tinyarea
a) ndte=55000
b) ndte=50000

dhmax= 8.91685e-5 m

my directory for the experiments: /users/dor/armn/jfl/local1/REVP_17oct2018/

**Comment by JFLemieux73** [comment]
Ok I will take care of comparing against the standard evp and update the documentation.

**Comment by JFLemieux73** [comment]
Mads,

I wanted to clone again the code for this PR to make some final tests. 
 
The revp branch code does not compile anymore (I think because some of the code in this branch might have changed since the PR).
 
Could you please add your REVP changes to the current master code and submit a new PR (or resubmit this one) so that I can make these tests?
 
Thanks

**Comment by eclare108213** [comment]
superseded by #218 and #219

**Pull request closed without merging**
