### PR TITLE
FSD updates for icepack.

### PR DESCRIPTION
**Pull request by dabail10**
For detailed information about submitting Pull Requests (PRs) to the CICE-Consortium,
please refer to: <https://github.com/CICE-Consortium/About-Us/wiki/Resource-Index#information-for-developers>

## PR checklist
- [X] Short (1 sentence) summary of your PR: 
This PR only updates the calls for the Icepack FSD bug fixes. https://github.com/CICE-Consortium/Icepack/pull/424
- [X] Developer(s): 
cmbitz (C. Bitz)
- [X] Suggest PR reviewers from list in the column to the right.
- [X] Please copy the PR test results link or provide a summary of testing completed below.
https://github.com/CICE-Consortium/Test-Results/wiki/cice_by_hash_forks#8d8a2d7db8bc7021c2c3134653ffa2fddacb66a3
- How much do the PR code changes differ from the unmodified code? 
    - [ ] bit for bit
    - [ ] different at roundoff level
    - [X] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [X] Yes
    - [ ] No
- Does this PR update the Icepack submodule?  If so, the Icepack submodule must point to a hash on Icepack's main branch.
    - [X] Yes
    - [ ] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [X] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [ ] Yes
    - [X] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [X] No 
- [X] Please provide any additional information or relevant details below:
This change was documented in the Icepack PR and is answer changing for all FSD active cases. This is just adding the hooks to CICE to call the new icepack interfaces.

### CODE REVIEW

**Review by apcraig — COMMENTED** [review]
Lets set wlat(:)=c0 somewhere in one of the init flux routines.  Some compiler checks will gag if an unset variable is passed into a subroutine.

**Comment by apcraig** [comment]
FSDmods have been merged into Icepack.  Please update Icepack in this PR and I'll do a final review before merging.  I ran these changes with Icepack changes on cheyenne and everything should be working as expected, see https://github.com/CICE-Consortium/Icepack/pull/424.  Thanks.

**Comment by dabail10** [comment]
I have fast-forwarded to CICE main which includes the latest icepack version.

**Comment by apcraig** [comment]
You also need to update Icepack explicitly to include the fsdmods.  The current CICE has the latest Icepack prior to the fsdmods, this PR needs to update Icepack to include the fsdmods PR that was merged to Icepack last night.

**Comment by dabail10** [comment]
Sorry, I was confused about that piece. Just updated to include the latest Icepack.

**Review by apcraig — APPROVED** [review]
I checked the code + PR out, compared it to my earlier test sandbox, and everything looks good.  Will merge soon unless anyone says wait.

**Pull request merged**
