### PR TITLE
Update CICE namelist implementation

### LINKED ISSUE #676: Namelist implementation issues
Recent changes to the CICE namelist implementation to trap bad namelist inputs is failing with the NAG compiler.  After some debugging, this comes down to a few issues

- The new feature leverages trapping bad lines with the iostat flag in the read namelist command.  But that iostat flag is also used to cycle thru the namelist file to find the correct group in some cases.
- Most compilers seem to reopen the namelist file in the place where it was most recently closed.  NAG does not do that, it rewinds the file.
- As currently coded, there is an assumption (mostly in ice_init) that namelist groups occur in a particular order.  That is not documented.  In other parts of the code, the namelist group could be in an arbitrary order.  The required order seems to be more-or-less fortuitously followed by users and is implemented in just the perfect order in the standalone code.

The new feature that was added to trap bad namelist lines happens to work on most compilers because

- The namelist groups appear in just the right order in the standalone testing to not require cycling in the file.
- Most compilers do not rewind the namelist file when reopening, so there is no cycling of the file to find the right group.  
- The iostat command happens to only be in use to trap bad lines in this case.

But NAG rewinds the file, so it's trapping the "line" error during normal cycling.  I think there are three possible options to move things forward,

1. Keep the current implementation which has some (but not all) required order of the namelist groups and document that.
2. Generalize the implementation, so there is no required order.  That would mean we'd have to rewind the namelist file anytime we open it and we'd have to cycle thru the groups (as we do now for some of the groups) until we find the right one for all namelist groups.
3. Formalize the order of all namelist groups.  To do this robustly, we'd want to open the namelist file once and leave it open.  The groups would have to always be in a particular order from start to end.  We would document this.

Only option 3 will allow us to trap and write a bad line in the namelist group.  With option 1 or 2, we'd need to use the iostat to cycle thru the groups and we couldn't trap an error on a single line of the group...  unless we check the iostat value and are able to robustly determine that certain values mean certain things and that it's uniform across all compilers.  I don't think the iostat values are consistent across compilers.

Maybe there are other options.  How should we proceed in terms of options 1, 2, or 3 at this point?  We probably want to fix this soon-ish, even if that only means reverting back to what we had before (option 1) since the code is broken on NAG at the moment.

@dabail10, @eclare108213 @daveh150 @phil-blain

### PR DESCRIPTION
**Pull request by apcraig**
## PR checklist
- [X] Short (1 sentence) summary of your PR: 
    Update CICE namelist implementation
- [X] Developer(s): 
    apcraig
- [X] Suggest PR reviewers from list in the column to the right.
- [X] Please copy the PR test results link or provide a summary of testing completed below.
    Full test suites on izumi and cheyenne, all OK.  https://github.com/CICE-Consortium/Test-Results/wiki/cice_by_hash_forks#33a3c2bd4107a9d566078bdea3a6a40e8903f3ef
- How much do the PR code changes differ from the unmodified code? 
    - [X] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [X] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [X] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [ ] Yes
    - [X] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [X] No 
- [X] Please provide any additional information or relevant details below:

See #676 for more details.  This is option 2 on that issue, generalize the implementation so namelist groups can be read in any order.  That was tested on NAG and it works as expected there.  Closes #676 if accepted.

- Update the namelist read to make the group order flexible.
- Remove recent update to namelist read that traps bad lines, it conflicts
  with flexibility to read groups in random order picked up by NAG.
- change print* statements to write(nu_diag,*)

### CODE REVIEW

**Comment by apcraig** [comment]
I decided to code up option 2 in #676.  If we decide to go a different direction with namelist, we can close this PR and I'm happy to recode as needed.

**Review by eclare108213 — COMMENTED** [review]
This looks fine to me, as long as it works as intended.  Some of those print statements have been in there forever!  I always have trouble finding the compare-source-codes functionality in github - how do I compare this PR with the code prior to the namelist PR #671?

**Comment by phil-blain** [comment]
>  how do I compare this PR with the code prior to the namelist PR #671?

You can construct the URL yourself, as long as you know the commit hashes:
~~~
$ git log --oneline upstream/main -5
dfc6a113 (upstream/main, upstream/HEAD) Add CESM1_PIO for fill value check (#675)
4c9024c4 NUOPC/CMEPS cap updates (#670)
ddc1cfcc Main namelist debug (#671)
2b851261 (fix-output-conversion-errors) nuopc/cmeps driver updates (#668)
162aee96 Fix multi-pe advection=none bug (#664)
~~~

OK, the commit hash of the squash-merge for #671 is ddc1cfcc and the  parent of ddc1cfcc is 2b851261. Now, the commit hash of the tip of Tony's branch for this here PR is https://github.com/CICE-Consortium/CICE/pull/677/commits/33a3c2bd4107a9d566078bdea3a6a40e8903f3ef (see above in the PR page).

So the compare URL is https://github.com/CICE-Consortium/CICE/compare/2b851261..33a3c2bd4107a9d566078bdea3a6a40e8903f3ef (it works with either full or abbreviated hashes). Note that that view will also show changes made to master in the meantime, i.e. 4c9024c4 and dfc6a113.

Hope that helps:)

**Comment by eclare108213** [comment]
Awesome.  Amazing.  Etc.  
Thanks!

**Review by eclare108213 — APPROVED** [review]

**Review by dabail10 — APPROVED** [review]
Looks good. It is really only the namelists in ice_init.F90 that are the problem. The others are in different modules and ice_in gets rewound to the top. Nonetheless it is good to be consistent.

**Comment by apcraig** [comment]
@dabail10, that's correct.  In fact, I only use rewind when we read a namelist and didn't just open the file.  The namelists in ice_init were the ones that had to be in a certain order before (undocumented).  The others already worked fine in any order.

**Pull request merged**
