### PR TITLE
Add ICE_MACHINE_QUEUE to additional machine environment files

### PR DESCRIPTION
**Pull request by mattdturner**
The PR that added --queue neglected to define ICE_MACHINE_QUEUE for servers that do not use a queue system.  This PR fixes that.

- Developer(s): Matt Turner

- Please suggest code Pull Request reviewers in the column at right.

- Are the code changes bit for bit, different at roundoff level, or more substantial? bfb

- Is the documentation being updated with this PR? (Y/N) N
If not, does the documentation need to be updated separately at a later time? (Y/N) N
Note: "Documentation" includes information on the wiki and .rst files in doc/source/, 
which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/.

- Other Relevant Details:

### CODE REVIEW

**Comment by eclare108213** [comment]
@anders-dc travisCI fails on this PR.  It looks like it was working okay, but timed out at the end.  How do we say "try again" for travisCI?

**Comment by anders-dc** [comment]
Hi @eclare108213, if you press the **Details** button next to the travis check that failed, you are taken to the build log.

screen shot 2018-06-07 at 17 30 00

On the build page on travis-ci.org there's a **Restart build** button.

screen shot 2018-06-07 at 17 28 22

**Comment by eclare108213** [comment]
Thanks for the quick response.  I must not have permission to do this.

tmp

**Comment by anders-dc** [comment]
Strange. I have, and I've triggered the restart.

**Comment by eclare108213** [comment]
I tested this with pinto and it works.  Other machines will need to be tested but for now I'll go ahead and merge.

**Pull request merged**
