### PR TITLE
Fix single channel debug failure, Update github actions testing

### PR DESCRIPTION
**Pull request by apcraig**
## PR checklist
- [X] Short (1 sentence) summary of your PR: 
    Fix single channel debug failure, Update github actions testing
- [X] Developer(s): 
    apcraig
- [X] Suggest PR reviewers from list in the column to the right.
- [X] Please copy the PR test results link or provide a summary of testing completed below.
    Full test suite run on Derecho with intel, cray, gnu.  All results look good.  https://github.com/CICE-Consortium/Test-Results/wiki/cice_by_hash_forks#28cb2baff01e4338e73be5c07721d2bc99f682e2
- How much do the PR code changes differ from the unmodified code? 
    - [X] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [X] No
- Does this PR update the Icepack submodule?  If so, the Icepack submodule must point to a hash on Icepack's main branch.
    - [ ] Yes
    - [X] No
- Does this PR add any new test cases?
    - [X] Yes, changes a single channel test to use debug flags
    - [ ] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [ ] Yes
    - [X] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [X] No 
- [X] Please provide any additional information or relevant details below:

Fixes a bug found during testing in #921, but unrelated to #921.  The single channel test was failing on MPI min/max with Fortran "huge" due to the lack of valid values.  Changed use of "huge" to local large values.

Also fixed a problem in floating point trapping with Github Actions, seems to be related to changes from MacOS 12.6.9 to 12.7.2.

### CODE REVIEW

**Comment by apcraig** [comment]
Currently debugging github actions results

**Review by eclare108213 — APPROVED** [review]
This took a bit of sleuthing - thanks!

**Comment by apcraig** [comment]
Doing additional testing now.  Once those results are available, this should be ready to merge if approved.

**Comment by TillRasmussen** [comment]
Out of curiosity was huge(0.0_dbl) too big a number?

**Review by TillRasmussen — APPROVED** [review]

**Comment by apcraig** [comment]
> Out of curiosity was huge(0.0_dbl) too big a number?

Not entirely sure.  huge(0.0_dbl) doesn't cause any problems in general.   But the single channel case has no valid NLAT, so huge (or something close to it) gets passed into the MPI reduction and that's where there is a problem.   I don't know if there is a problem with rounding up or what.  I didn't really look into the details, the simple change I made fixed the problem.

**Comment by apcraig** [comment]
I ran full test suite on Derecho intel, cray, gnu with these mods plus mods from #921.  Results look good.  Will merge this PR now.  #921 still pending.

**Pull request merged**
