### PR TITLE
Precision

### PR DESCRIPTION
**Pull request by dabail10**
For detailed information about submitting Pull Requests (PRs) to the CICE-Consortium,
please refer to: <https://github.com/CICE-Consortium/About-Us/wiki/Resource-Index#information-for-developers>

## PR checklist
- [X] Short (1 sentence) summary of your PR: 
Add history_precision namelist option.
- [X] Developer(s): 
dabail10 (D. Bailey)
- [X] Suggest PR reviewers from list in the column to the right.
- [X] Please copy the PR test results link or provide a summary of testing completed below.
Test-Results.wiki/cice_dev/c38a514361.cheyenne.intel.20-05-14.154337.0.md
- How much do the PR code changes differ from the unmodified code? 
    - [X] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [X] No
- Does this PR add any new test cases?
    - [X] Yes
    - [ ] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [X] Yes
    - [ ] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [ ] No 
- [X] Please provide any additional information or relevant details below:
The history file answers will only change when turning on double-precision history output, that is history_precision = 8.

### CODE REVIEW

**Comment by dabail10** [comment]
I was not able to get the pio interfaces working. I am just putting in the precision changes so we have them. It works with binary and netcdf. I can back out the Macros and env changes, but this is what I did to try to get everything to compile. Is this not the way we want to go?

**Comment by apcraig** [comment]
The Macros and env changes I've made are similar, but not quite the same.  Nothing wrong with what you have, but my mods are slightly different.  It would be easier for me if you removed your changes.

**Comment by dabail10** [comment]
Ok. Changes made.

**Comment by apcraig** [comment]
There is also a change in cice.build that could be reverted if you have a chance.  thanks.

**Comment by dabail10** [comment]
Is there any systematic way that the abort_flag number is set? Why does it jump from 21 to 30?

**Comment by apcraig** [comment]
The abort_flag number is not important as long as it's not zero.  It's better if it's unique.  In fact, as presently implemented it will be the last error encountered if you have multiple.  It would be better for this to be a character string that somehow accumulates the error list, but I don't think that's important to do at this point.  The main point is that the errors are all written then later the code aborts if 1 or more is found.  The abort_flag could be a logical too.  My making it a number, I thought it would provide more info, and it does, but not as much as it might.  Thanks!

**Comment by dabail10** [comment]
One more dumb question. Why are there two abort_flag settings done after the print statements?

**Comment by apcraig** [comment]
Not sure, I suspect it's historical.  Some checks may have been originally done before the namelist is written to the log files and others after.  That order probably was not changed when the abort_flag was implemented.  We could probably clean that up a bit, but I'm not sure it's important.  Actually, the kevp_kernel flag (21) probably should remain after the output because we want to see the original setting in the output before it's potentially changed.  abort_flag=20 could be moved up or they all could be moved down.

**Comment by apcraig** [comment]
I think this is ready to merge.  @dabail10 any outstanding issues?  @eclare108213 do you want to have a review?  I am a little eager to merge this so I can pull it into my pio standalone testing and address any conflicts or other issues.  If we want to wait a bit to merge this, I can wait (or I could merge from this dev branch to do some initial testing).

**Pull request merged**
