### PR TITLE
Added k1 (basal stress parameter) in namelist, new machine

### PR DESCRIPTION
**Pull request by phil-blain**
Added k1 landfast parameter to namelist and added scripts for Philippe's machine

- Developer(s):Philippe Blain

- Please suggest code Pull Request reviewers in the column at right. @eclare108213 

- Are the code changes bit for bit, different at roundoff level, or more substantial?  BFB

- Please include the link to test results or paste the summary block from the bottom of the testing output below.
34 of 83 tests PASSED
0 of 83 tests FAILED
27 of 83 tests PENDING
(I don't know why some tests are pending...)

- Does this PR create or have dependencies on Icepack or any other models? No

- Is the documentation being updated with this PR? (Y/N) Yes
If not, does the documentation need to be updated separately at a later time? (Y/N)

Note: "Documentation" includes information on the wiki and .rst files in doc/source/, 
which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/.

- Other Relevant Details:

### CODE REVIEW

**Comment by JFLemieux73** [comment]
I think it is ok just to have k1. The results are not very sensitive to k2.

**Comment by phil-blain** [comment]
Yes well after I ran 
`./cice.setup --suite base_suite -g gx1 -m cesium -p 1x1 -s diag1 --testid firsttest`
the results.csh script shows :
34 of 83 tests PASSED
0 of 83 tests FAILED
27 of 83 tests PENDING

**Comment by eclare108213** [comment]
I see.  The base suite tests a bunch of different configurations, including different numbers of processors and also tests with and without '-s diag1'.  If cesium only has 1 core, then some of those multi-processors tests won't work, or possibly your specifying '-p 1x1' creates a conflict in the base_suite script.  I expect that '-s diag1' specifies those diagnostics for all of the tests, which should be okay but might cause some of the runs to time out.

**Comment by phil-blain** [comment]
Ah yes I understand (I'm new to all this!). I just restarted the base suite without the processor and diagnostic options. I have 12 cores so that should not be a problem.

**Comment by phil-blain** [comment]
The results of the base_suite are : 
```
32 of 91 tests PASSED
14 of 91 tests FAILED
25 of 91 tests PENDING
```

The failed tests are : 
```
FAIL cesium_intel_smoke_gx3_4x1_debug_diag1_run5day build
FAIL cesium_intel_smoke_gx3_4x1_debug_diag1_run5day run
FAIL cesium_intel_restart_gx3_8x2_debug build
FAIL cesium_intel_restart_gx3_8x2_debug run
FAIL cesium_intel_restart_gx3_4x4_iobinary build
FAIL cesium_intel_restart_gx3_4x4_iobinary run
FAIL cesium_intel_restart_gbox80_1x1_box2001 build
FAIL cesium_intel_restart_gbox80_1x1_box2001 run
FAIL cesium_intel_smoke_gx3_8x2 build
FAIL cesium_intel_smoke_gx3_8x2 run
FAIL cesium_intel_smoke_gx3_8x1_bgcskl_debug build
FAIL cesium_intel_smoke_gx3_8x1_bgcskl_debug run
FAIL cesium_intel_restart_gx1_8x1_bgczclim_medium build
FAIL cesium_intel_restart_gx1_8x1_bgczclim_medium run
```

The pending tests are :
```
PEND cesium_intel_decomp_gx3_4x2x25x29x5_squarepop run
PEND cesium_intel_decomp_gx3_4x2x25x29x5_squareice run
PEND cesium_intel_decomp_gx3_4x2x25x29x5_slenderX2 run
PEND cesium_intel_decomp_gx3_4x2x25x29x5_slenderX1 run
PEND cesium_intel_decomp_gx3_4x2x25x29x5_roundrobin run
PEND cesium_intel_decomp_gx3_4x2x25x29x5_sectcart run
PEND cesium_intel_decomp_gx3_4x2x25x29x5_sectrobin run
PEND cesium_intel_decomp_gx3_4x2x25x29x5_spacecurve run
PEND cesium_intel_decomp_gx3_4x2x25x29x5_rakeX2 run
PEND cesium_intel_decomp_gx3_4x2x25x29x5_rakeX1 run
PEND cesium_intel_decomp_gx3_4x2x25x29x5_rakepop run
PEND cesium_intel_decomp_gx3_4x2x25x29x5_rakeice run
PEND cesium_intel_restart_gx1_40x4_droundrobin_medium test 
PEND cesium_intel_restart_tx1_40x4_dsectrobin_medium test 
PEND cesium_intel_restart_gx3_4x4 test 
PEND cesium_intel_restart_gx3_6x2_alt01 test 
PEND cesium_intel_restart_gx3_8x2_alt02 test 
PEND cesium_intel_restart_gx3_4x2_alt03 test 
PEND cesium_intel_restart_gx3_4x4_alt04 test 
PEND cesium_intel_restart_gx3_4x4_alt05 test 
PEND cesium_intel_restart_gbox128_4x2 test 
PEND cesium_intel_restart_gbox128_4x2_boxdyn test 
PEND cesium_intel_restart_gbox128_2x2_boxadv_short test 
PEND cesium_intel_restart_gbox128_4x4_boxrestore test 
PEND cesium_intel_restart_gx1_4x2_bgcsklclim_medium test 
```

I don't know why the tests fail...

**Comment by apcraig** [comment]
@phil-blain have you tried to do the same suite on the master?  my guess is that will fail the same way and that there are just some porting issues that may need to be sorted out.  I would encourage you to look into that. 

I can run a test suite on a known working platforms in the mean time, just to validate the changes, although I'm not really worried about the code changes here.

**Comment by apcraig** [comment]
All tests are passing for me on conrad with 4 compilers.  And everything is bit-for-bit with master.  I am going to merge this now.

@phil-blain , feel free to email me at anthony.p.craig@gmail.com if I can help or answer any questions about the problems you ran into when testing on cesium.

**Pull request merged**
