### PR TITLE
doc: correct description of box2001 test

### PR DESCRIPTION
**Pull request by phil-blain**
## PR checklist
- [x] Short (1 sentence) summary of your PR: 
doc: correct description of box2001 test
- [X] Developer(s): 
        P Blain.
- [x] Suggest PR reviewers from list in the column to the right.
- [x] Please copy the PR test results link or provide a summary of testing completed below.
    **no tests; doc fix.**
- How much do the PR code changes differ from the unmodified code? 
    - [X] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [X] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [X] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [X] Yes
    - [ ] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [ ] No 
- [x] Please provide any additional information or relevant details below:

    The documentation states that this test case sets 'coriolis' to zero,
    but 'configuration/scripts/options/set_nml.box2001' sets 'coriolis' to 'constant'.
    Fix the documentation to be in line with the code.

### CODE REVIEW

**Comment by phil-blain** [comment]
@JFLemieux73 good idea. I've added it and also in the Case settings section.

**Comment by apcraig** [comment]
In preparation for the next release, I will merge this tomorrow morning unless any other concerns are expressed before then.  Thanks.

**Comment by JFLemieux73** [comment]
In Hunke 2001 it is written: For these simulations the Coriolis parameter is taken to be constant...
In the table: f Coriolis parameter 1.46 x 10-4 s-1

We could set f to 0 as long as it is consistent with the doc. I think the 3 islands are not there either (am I right?). We could just say this test case is inspired by the test case in Hunke 2001.

**Comment by eclare108213** [comment]
Interesting.  Thanks for checking!  Then let's keep it as the constant value.  You're right, the islands aren't there, but they aren't the important part of the test - that's getting the forcing the same.  So I think this is fine.  Thank you!

**Pull request merged**
