### PR TITLE
Corrects icepack initialization for bgc.

### PR DESCRIPTION
**Pull request by njeffery**
Adds missing namelist fields.

Also added gx1 tests for zbgc (bgc,bgcgx1) and skl (bgcskl,sklgx1)
Required nutrient forcing filenames are hard coded (nitrate_climatologyWOA_gx1v6f.nc and silicate_climatologyWOA_gx1v6f.nc)
Namelist field bgc_data_dir needs to be properly specified.
Note  *gx1 zbgc test is really slow and fails on wolf*
Tested with icepack@1e5f2fa

### CODE REVIEW

**Comment by eclare108213** [comment]
@njeffery Thank you for adding tests!  Can these be run with gx3, even if the results aren't realistic (nothing about gx3 is realistic)?  Maybe set nitrate and silicate forcing as constants for short-time runs?

Your Icepack conflicts with the one on master, and I think we can't merge this PR like this.  Could you update to the master version, please?

We'll need to treat the forcing files and directories consistently with other forcing in the code.  This is a little different from how we've done things in the past.

And finally, we will need to update the documentation for all of this.

**Comment by njeffery** [comment]
Elizabeth: I'll work on updating to master and resubmitting.  There's a flag to use constant ocean forcing which should be fine for a gx3 test.  I can add those tests.   My biggest concern is that the gx1 zbgc test fails  on wolf during a call to either ice_restart, ice_diagnostics or ice_forcing (not sure which) on a model day that changes based on the length of the submitted run.  It also seems unusually slow to me.


n

________________________________

**Comment by eclare108213** [comment]
Sounds like a memory access issue.  If we had a gx3 test, it would be easier to debug...  or maybe gx3 wouldn't fail, and that would be a useful data point too.  How far into the gx1 run does it fail?  Do bgc restarts work?

**Comment by eclare108213** [comment]
@njeffery Let me know when you might have a chance to sit down together and talk through this.  Maybe I can help?

**Comment by duvivier** [comment]
@njeffery I have the files downloaded and will add them to the tarballs shortly. Is there anything else you need me to comment on at this time or is the review on hold till the memory issues are sorted?

**Comment by njeffery** [comment]
Thanks @duvivier.  The review is on hold due to the memory issues, though I suspect they are already present in master.

**Comment by duvivier** [comment]
@njeffery Just a quick question here since I'm making sure these files (and all the others) are updated on the ftp but in the right directories. 

In /CICE/cicecore/cicedynB/general/ice_forcing_bgc.F90 it appears that For both the nitrate_climatologyWOA_gx1v6f.nc and silicate_climatologyWOA_gx1v6f.nc files it should look for them in bgc_data_dir, which the user would need to specify in the namelist. 

Can you specify the directory structure we should use? The current COREII forcing we provide uses this structure:
CICE_data/forcing/gx1/COREII/{4xDAILY,MONTHLY}/

**Comment by njeffery** [comment]
Hi Alice,


How about


CICE_data/forcing/gx1/WOA/MONTHLY?


We could also add "bgc" if that would be useful.


CICE_data/forcing/gx1/bgc/WOA/MONTHLY


-nicole

________________________________

**Comment by eclare108213** [comment]
My intent was to get rid of bgc_data_dir, and just use ocn_data_dir for the bgc data.  Is there any chance we'd have atm bgc data?  Given that change, I'd prefer this directory structure:
CICE_data/forcing/gx1/WOA/MONTHLY

**Comment by njeffery** [comment]
Elizabeth,

We have dust (iron) and BC now from the atmosphere.  I expect macro-nutrients in the not so distant future.


nicole

________________________________

**Comment by eclare108213** [comment]
What is the source of the atmo data?

**Comment by njeffery** [comment]
CAM output.

________________________________

**Comment by duvivier** [comment]
I'm also inclined to the WOA/MONTHLY format instead of adding bgc in there just for the flexibility. I'll go with that and hopefully we can eliminate bgc_data_dir that way.

**Comment by eclare108213** [comment]
sounds good to me

**Comment by duvivier** [comment]
Nicole, we want to have all new files added use the date created in case there are future updates. Is there any problem with me appending yyyyddmm to these (20180814 is when you emailed them to me)? You could also re-make them and send them to me with the date? Then a softlink could just be made in the data directory for the dated file name to the general file name.

**Comment by njeffery** [comment]
Hi Alice,


I made these files back in 2015.  Can you append the date 20150107 ?


Thanks

n

________________________________

**Comment by duvivier** [comment]
These files have been added to the CICE forcing and are now available on the ftp (CICE_data_new.tar.gz, CICE_data_forcing_gx1_MONTHLY.tar.gz, and CICE_data_all.tar.gz all have the new files, but people with the data already can just download the first file). 

I've added documentation to the wiki about new files as well for these and setting the stage for future additions. https://github.com/CICE-Consortium/CICE/wiki/CICE-Input-Data

Let me know if there's anything else you need from me for this PR.

**Comment by eclare108213** [comment]
E's summary of where this PR is:
Includes new tests for zbgc and also skeletal layer bgc on both gx3 and gx1.  

(Some of?) these tests utilize new forcing files which are hard-coded.  The files need to be handled the same way as other forcing files.  @duvivier updated the file names on the ftp site, adding dates.  

Documentation still needs to be added for the new tests.  It's not clear from this github conversation, which tests have forcing data in files and which use internally generated data.   It looks like gx1 has files and gx3 doesn't?

The gx1 configuration crashes on wolf, which @njeffery says might be due to a problem already in master.   We need to run several sets of tests, and post the results to the wiki:

1. a complete set of these new tests using the most recent file updates.  It would be nice to run the tests on the various machines used for our regular testing as well as on wolf, to see if the problem is isolated to wolf or is more general.  
2. run the test suite on wolf without these changes, to see if the issue is already on master.

**Comment by eclare108213** [comment]
@njeffery is running the various tests with debug flags on as a first step to tracking down the issue with this part of the code.

**Comment by apcraig** [comment]
Is this redundant with #207 or are those two separate things?

This branch will need to be updated to master to address changes in how tracers are handled (as namelist, not cpps).  This will require changes to set_env and set_nml files.  Sorry about that.  Let me know if you need some help.

**Comment by eclare108213** [comment]
@njeffery   Is this PR is superseded by #207, so I can close it?

**Comment by njeffery** [comment]
Yes. Thanks Elizabeth.

n

________________________________

**Pull request closed without merging**
