### PR TITLE
Send broadband fswthrun by categories to coupler.

### PR DESCRIPTION
**Pull request by dabail10**
For detailed information about submitting Pull Requests (PRs) to the CICE-Consortium,
please refer to: <https://github.com/CICE-Consortium/About-Us/wiki/Resource-Index#information-for-developers>

## PR checklist
- [X] Short (1 sentence) summary of your PR: 
This just introduces two new variables, send_i2x_per_cat and fswthrun_ai for sending to the coupler or not.
- [x] Developer(s): 
dabail10 (D. Bailey)
- [X] Suggest PR reviewers from list in the column to the right.
- [X] Please copy the PR test results link or provide a summary of testing completed below.
  https://github.com/CICE-Consortium/Test-Results/wiki/cice_by_mach_forks#cheyenne
- How much do the PR code changes differ from the unmodified code? 
    - [X] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [X] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [X] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [ ] Yes
    - [X] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [X] No 
- [X] Please provide any additional information or relevant details below:
This is an internal flag that is activated by the cap/driver and not a namelist variable. If the coupler requires this then it will turn it on. Another update is coming from the NUOPC cap that uses this. This is related to issue #482.

### CODE REVIEW

**Comment by apcraig** [comment]
Are changes needed in the cap as well?  How will send_i2x_per_cat be set?  send_i2x_per_cat is a very CESM-centric name.  Would something like "save_fswthrunByCat"  or similar be better?

**Comment by dabail10** [comment]
The cap will receive a flag from the coupler/mediator calling for the fluxes by category. I will update the NUOPC cap in a separate PR. The CICE standalone cap does not need to be updated. I am happy to rename the logical flag.

**Comment by apcraig** [comment]
@dabail10, sounds good.  I'd wait for some other reviews before deciding on the name of the flag.

**Comment by dabail10** [comment]
send_i2x_per_cat is declared in ice_flux.F90 and set to .false. by default. It is not meant to be read in via the namelist.

**Comment by apcraig** [comment]
@eclare108213, @dabail10 is this ready to approve/merge?

**Comment by apcraig** [comment]
@eclare108213, it's hardwired for now.  The changes in the NUOPC cap still need to be implemented to turn this feature on.

**Pull request merged**
