### PR TITLE
Allow kmt variable name of "mask" and different size netcdf 2d reads

### PR DESCRIPTION
**Pull request by anton-seaice**
## PR checklist
- [ ] Short (1 sentence) summary of your PR: 
    This is two bits of tidy up in the grid infrastructure, to make further extensions easier. I'm doing this PR now so the changes are easier to review.
- [ ] Developer(s): 
    @anton-seaice
- [ ] Suggest PR reviewers from list in the column to the right.
@apcraig
- [ ] Please copy the PR test results link or provide a summary of testing completed below.
    Still running, will update next week
- How much do the PR code changes differ from the unmodified code? 
    - [x] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [x] No
- Does this PR update the Icepack submodule?  If so, the Icepack submodule must point to a hash on Icepack's main branch.
    - [ ] Yes
    - [x] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [x] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [x] Yes
    - [ ] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [ ] No 
- [ ] Please document the changes in detail, including _why_ the changes are made.  This will become part of the PR commit log.

This change allows for a single processor read of netcdf variables that are not of size nx_global by ny_global. This is to make it easier to extent the ice_grid routines.

This changes allows the mask variable in the kmt netcdf file to be called "mask" instead of "kmc". Both options now work.

This change splits reading the mask and grid into seperate subroutines, so the routine can be reused independently later.

### CODE REVIEW

**Comment by apcraig** [comment]
This all looks pretty reasonable.  When you have test results and feel it's ready, let me know.  I will run some independent testing, review, and merge.  Thanks!

**Comment by anton-seaice** [comment]
I ran the whole base_suite, i needed to extend the run-time for several tests ? And sometimes by quite a big increase in time.

The results were bit for bit / no regressions were found.

This is ready to merge from my perspective

**Comment by eclare108213** [comment]
> I ran the whole base_suite, i needed to extend the run-time for several tests ? And sometimes by quite a big increase in time.

@anton-seaice Were there corresponding runs with debugging flags on for any of the slow tests?  Could there be NaNs in those cases?

**Comment by anton-seaice** [comment]
Sorry - my comment wasn't clear!

I needed to increase the run-time for the tests both before and after the change. It was the tests with small core counts that seemed to be more affected, so I wonder if maybe our job scheduler is different or compiler options or something need adjusting. It's not related to this change.



> @anton-seaice Were there corresponding runs with debugging flags on for any of the slow tests? Could there be NaNs in those cases?

It doesn't look like base_suite has tests where the only different between two tests is just debug.

**Comment by apcraig** [comment]
I know some of the tests were timing out.  If we add "short" and so forth to the test, we lose the regression testing because the case name changes.  I can live with that but want to avoid doing that often.  Lets go with it this time, but maybe we can think about whether there are other ways to set the requested queue time without it changing the casename in the future.  I'll think about it too.

**Comment by apcraig** [comment]
Ran the quick suite on derecho with 6 compilers and all tests pass, tested done with #986 . Will merge this week, trying to merge fsd mods first.

**Review by apcraig — APPROVED** [review]

**Pull request merged**
