### PR TITLE
Update emissivity to 0.985 and set nblyr default to 1

### PR DESCRIPTION
**Pull request by apcraig**
## PR checklist
- [X] Short (1 sentence) summary of your PR: 
    Update emissivity to 0.985 and set nblyr default to 1
- [X] Developer(s): 
    apcraig
- [X] Suggest PR reviewers from list in the column to the right.
- [X] Please copy the PR test results link or provide a summary of testing completed below.
    Full test suites run on cheyenne on 3 compilers, most results are NOT bit-for-bit.
https://github.com/CICE-Consortium/Test-Results/wiki/cice_by_hash_forks#c4b9051c28db9ab818669133a72be687d8846c0e
- How much do the PR code changes differ from the unmodified code? 
    - [ ] bit for bit
    - [ ] different at roundoff level
    - [X] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [X] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [X] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [X] Yes
    - [ ] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [ ] No 
- [X] Please provide any additional information or relevant details below:

See #249 

Change emissivity default to 0.985 (from 0.95)
Change nblyr default to 1 (from 7)
Add nblyr=7 to set_nml.zsal
Update Icepack to include emissivity default changes
Update documentation as needed

### CODE REVIEW

**Comment by apcraig** [comment]
Do we need/want to do a QC test?  Would we expect it to pass?

**Comment by eclare108213** [comment]
A QC test would certainly be interesting.  I wouldn't expect it to pass in stand-alone mode based on prior sensitivity tests, but it might pass.  For completeness, I think it's a good idea to run a QC test.

**Comment by apcraig** [comment]
The QC test passed on cheyenne.  I'm not sure whether this is a good or bad outcome.

INFO:__main__:Running QC test on the following directories:
INFO:__main__:  /glade/scratch/tcraig/CICE_RUNS/cheyenne_intel_smoke_gx1_36x1_medium_qc.qc_base
INFO:__main__:  /glade/scratch/tcraig/CICE_RUNS/cheyenne_intel_smoke_gx1_36x1_medium_qc.qc_test
INFO:__main__:Number of files: 1460
INFO:__main__:2 Stage Test Passed
INFO:__main__:Quadratic Skill Test Passed for Northern Hemisphere
INFO:__main__:Quadratic Skill Test Passed for Southern Hemisphere
INFO:__main__:Quality Control Test PASSED

**Comment by eclare108213** [comment]
Was this run with JRA forcing?  Then it's good.  I'd expect it to fail with the old forcing, which is a lot of the reason for moving to JRA. Sensitivities using the old forcing had the wrong sign!

**Comment by apcraig** [comment]
Yes, this is with JRA55 forcing.

**Review by eclare108213 — APPROVED** [review]
I think it's fine to merge this, assuming that the issues that @dabail10 is turning up are related to configuration settings specific to his tests rather than these code changes.

**Comment by dabail10** [comment]
This was a problem related to my setup and not the emissivity value change.

**Review by dabail10 — APPROVED** [review]

**Comment by dabail10** [comment]
I just verified that even with emissivity of 0.95, I cannot do a run crossing 1996 to 1997 (starting in 1995) with my JRA forcing. I believe there is a leap year related issue here. I will open a separate issue.

**Pull request merged**
