### PR TITLE
Refactor boxslotcyl advection test to use icepack parameters

### PR DESCRIPTION
**Pull request by phil-blain**
## PR checklist
- [x] Short (1 sentence) summary of your PR: 
 After I did #254, I realized that two constants I had defined actually already existed in icepack_parameters. I updated the code to use them to reduce duplication.
- [x] Developer(s): 
        Philippe Blain
- [x] Suggest PR reviewers from list in the column to the right. @eclare108213 
- [x] Please copy the PR test results link or provide a summary of testing completed below.
    base_suite results: 
```
214 of 214 tests PASSED
0 of 214 tests FAILED
0 of 214 tests PENDING
```
- How much do the PR code changes differ from the unmodified code? 
    - [x] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [x] Yes (Is this what is meant here ? )
    - [ ] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [x] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/.)
    - [ ] Yes
    - [x] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [x] No 
- [ ] Please provide any additional information or relevant details below:

### CODE REVIEW

**Comment by phil-blain** [comment]
UCAR FTP is down...

**Comment by eclare108213** [comment]
Travis is failing on the NCAR ftp.  Did the filenames change with the new JRA55 data?

**Comment by apcraig** [comment]
Travis should be working.  Sometimes, the wget fails (for reasons I don't understand).  Usually if you trigger the build again, it works on the 2nd or 3rd try.  It looks like someone just triggered the build again.

**Comment by apcraig** [comment]
This can probably be merged straight-away.  @eclare108213 feel free to do that after you've had another look.  Travis worked on 2nd attempt.

**Comment by mattdturner** [comment]
> Sometimes, the wget fails (for reasons I don't understand)

Travis has issues with FTP.  

> the FTP protocol cannot be reliably used on our sudo-enabled Linux hosted infrastructure anymore.
Source: https://blog.travis-ci.com/2018-07-23-the-tale-of-ftp-at-travis-ci

I know our `.travis.yml` file has `sudo: false` included, but that doesn't seem to resolve the issue.  It is suggested to use `wget` with `http(s)`, or `sftp` to download the files.  I'm not sure if that is an option on the NCAR FTP.

**Pull request merged**
