### PR TITLE
New e3sm and e3smbgc namelist options

### PR DESCRIPTION
**Pull request by dabail10**
For detailed information about submitting Pull Requests (PRs) to the CICE-Consortium,
please refer to: <https://github.com/CICE-Consortium/About-Us/wiki/Resource-Index#information-for-developers>

## PR checklist
- [ ] Short (1 sentence) summary of your PR: 
    ENTER INFORMATION HERE
- [ ] Developer(s): 
    ENTER INFORMATION HERE
- [ ] Suggest PR reviewers from list in the column to the right.
- [ ] Please copy the PR test results link or provide a summary of testing completed below.
    ENTER INFORMATION HERE 
- How much do the PR code changes differ from the unmodified code? 
    - [ ] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [ ] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [ ] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [ ] Yes
    - [ ] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [ ] No 
- [ ] Please provide any additional information or relevant details below:

### CODE REVIEW

**Review by eclare108213 — COMMENTED** [review]
This looks reasonable to me.  Are there other configuration choices, e.g. forcing, that will also need to be set differently?  Maybe TBD.

**Comment by apcraig** [comment]
Just curious, do these run?

This probably belongs on the E3SM/Icepack dev branch of CICE that I suggested we create, but doesn't exist yet.  Lets discuss this afternoon.

**Comment by dabail10** [comment]
These do not run yet. Hence the draft PR. I have some additional questions about them.

Dave

**Comment by apcraig** [comment]
Please move this PR here, https://github.com/apcraig/CICE/tree/E3SMIcepackDEV

**Pull request closed without merging**
