### PR TITLE
Change default forcing to JRA55do, changes answers

### PR DESCRIPTION
**Pull request by apcraig**
## PR checklist
- [X] Short (1 sentence) summary of your PR: 
    Change default forcing to JRA55do, changes answers
- [X] Developer(s): 
    apcraig, dbailey, davidh
- [X] Suggest PR reviewers from list in the column to the right.
- [X] Please copy the PR test results link or provide a summary of testing completed below.
    full test suite run on cheyenne, all tests pass, most tests change answers (box cases and unit tests generally don't).  https://github.com/CICE-Consortium/Test-Results/wiki/cice_by_hash_forks#f9d3002c86e11ca18b06382fc2d0676c9a945223
- How much do the PR code changes differ from the unmodified code? 
    - [ ] bit for bit
    - [ ] different at roundoff level
    - [X] more substantial, should be same climate via QC testing
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [X] No
- Does this PR update the Icepack submodule?  If so, the Icepack submodule must point to a hash on Icepack's main branch.
    - [ ] Yes
    - [X] No
- Does this PR add any new test cases?
    - [X] Yes, changes forcing default and adds JRA55 tests
    - [ ] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [ ] Yes
    - [X] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [X] No 
- [X] Please provide any additional information or relevant details below:

This changes answers and all users will have to update the input data forcing to add JRA55do.

### CODE REVIEW

**Comment by apcraig** [comment]
I need to update the github actions testing, need to pull the new dataset.

**Comment by apcraig** [comment]
If we're going to do this, lets get this change in.  I'll need to update several machines with the new input data and we want to make this change well in advance of the release.  gx3, gx1, tx1 results will change.  If we're not going to do this, then lets just close the PR, and we can support the JR55do as an option.  Anyone changed their mind about moving this forward?  Anyone want to review the PR?

**Comment by eclare108213** [comment]
See discussion and results at https://github.com/CICE-Consortium/CICE/pull/831 and https://github.com/CICE-Consortium/CICE/pull/843

**Comment by eclare108213** [comment]
My inclination is to not make JRA55do the default, but to support it as an option, so that users don't have to download the data if the old JRA55 is sufficient for their purposes.  At some point in the future we might decide to make it the default, but if JRA55 is going away completely, perhaps we should wait for its replacement.  @dabail10 please weigh in.

**Comment by daveh150** [comment]
I agree that to minimize community disruption making JRA55do an option, and not the default, makes sense. We could have set_nml options for JRA55do. It is worth while to add a separate small test suite like a 'quick jra55do' for reference?

**Comment by dabail10** [comment]
This is a bit challenging. In a sense the original JRA55 datasets were a mistake. Most groups who use it do use the JRA55do which is specifically modified for running ice-ocean simulations. We use the JRA55do in CESM and I know a number of other groups who do this. So, in that sense I would vote for the JRA55do as the default. That's just my $0.02.

**Comment by eclare108213** [comment]
There are strong arguments on both sides, and so I'd like other team members to weigh in.  @CICE-Consortium/devteam 
The quest is whether to change from JRA55 to JRA55do as the default forcing in our releases.

PROs:  
- JRA55do is specifically modified for running ice-ocean simulations
- many groups are using it

CONs:  
- all users would have to download the new data set
- JRA55* will not continue to be supported and will likely be replaced with a different product

**Comment by TillRasmussen** [comment]
From DMI side there is no strong opinion about this. We primarily use ECMWF data and only use this data set for test when we push to the main branch.

**Comment by dupontf** [comment]
Same here, I would not change this just for our own testing. As long as there is a disclaimer that the dataset is provided for testing only and not scientific studies, it should be clear enough.

**Comment by eclare108213** [comment]
I think that making JRA55do the default forcing is too much of a disruption for not much gain.  We do not recommend that users run uncoupled/standalone production simulations.  If they want to do that, then they can set the forcing to JRA55do.  The Consortium would only be using it for our testing.  So my recommendation is to close this PR.  If we end up needing to make JRA55do the default, then we can reopen it or make a new one.

**Comment by apcraig** [comment]
We can consider this anytime in the future.  For now, we're leaving JRA55 forcing as is with JRA55do an option.

**Pull request closed without merging**
