### PR TITLE
Timeseries

### PR DESCRIPTION
**Pull request by eclare108213**
Generalized the timeseries.csh file to be able to use log files without a directory structure.

- Developer(s):  E. Hunke

- Please suggest code Pull Request reviewers in the column at right.

- Are the code changes bit for bit, different at roundoff level, or more substantial?  BFB

- Please include the link to test results or paste the summary block from the bottom of the testing output below.

- Does this PR create or have dependencies on Icepack or any other models?  no

- Is the documentation being updated with this PR? (Y/N)  yes
If not, does the documentation need to be updated separately at a later time? (Y/N)   no

Note: "Documentation" includes information on the wiki and .rst files in doc/source/, 
which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/.

- Other Relevant Details:
This can wait until after the release.

### CODE REVIEW

**Comment by duvivier** [comment]
@apcraig @eclare108213 
Is this something we're ready to merge? I think it would be good to include the timeseries tool with the release if possible.

**Comment by eclare108213** [comment]
I'm willing to go either way on this one.  The tool is in there now, it's just not as flexible without these changes.

**Comment by eclare108213** [comment]
I will merge - I think these changes make the tool more intuitive, as well as more flexible.

**Comment by duvivier** [comment]
I just checked the documentation with my local sphinx build. I think it's fine.

**Pull request merged**
