### PR TITLE
Convergence on ustar for CICE.

### PR DESCRIPTION
**Pull request by dabail10**
For detailed information about submitting Pull Requests (PRs) to the CICE-Consortium,
please refer to: <https://github.com/CICE-Consortium/About-Us/wiki/Resource-Index#information-for-developers>

## PR checklist
- [X] Short (1 sentence) summary of your PR: 
This is now an icepack option and adding it to CICE.
- [X] Developer(s): 
dabail10 (D. Bailey)
- [X] Suggest PR reviewers from list in the column to the right.
- [X] Please copy the PR test results link or provide a summary of testing completed below.
https://github.com/CICE-Consortium/Test-Results/wiki/cice_by_hash_forks#24a865bf83a94d5d2d98741eebd0634b79b84311
- How much do the PR code changes differ from the unmodified code? 
    - [X] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [X] Yes
    - [ ] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [X] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [X] Yes
    - [ ] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [ ] No 
- [X] Please provide any additional information or relevant details below:
Just adds the namelist parameter atmiter_conv to the CICE namelist.

### CODE REVIEW

**Comment by dabail10** [comment]
Not sure why the build the docs is failing.

**Comment by apcraig** [comment]
Unfortunately, I don't know how to retrigger the readthedocs build.  It looks to me like a problem on the rtd side.  If you can make a minor change like add or remove a blank line or space in documentation or any file, then commit and push, that will retrigger the rtd.  I wish we had a better way to handle rtd failures.  I can manually rerun the travis tests, but not rtd that I know.  Thanks.

**Comment by dabail10** [comment]
This looks like it is ready to merge.

**Comment by apcraig** [comment]
Sounds good, we can merge once at least one review is done.  I'm have looked at the implementation and think it's fine.  I think at least @eclare108213 or @proteanplanet should submit a review since they were involved in prior discussion.

**Pull request merged**
