### PR TITLE
add `Pstar` and `Cstar` to namelist

### PR DESCRIPTION
**Pull request by phil-blain**
## PR checklist
- [x] Short (1 sentence) summary of your PR: 
    Add `Pstar` and `Cstar` to namelist
- [x] Developer(s): 
    P. Blain
- [x] Suggest PR reviewers from list in the column to the right.
- [x] Please copy the PR test results link or provide a summary of testing completed below.
    **Tested that the new namelist values are correctly printed in the run log.**
- How much do the PR code changes differ from the unmodified code? 
    - [X] bit for bit (I guesss... I've always wondered about single vs double precision in the namelist...)
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [x] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [x] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [x] Yes
    - [ ] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [ ] No 
- [ ] Please provide any additional information or relevant details below:

### CODE REVIEW

**Comment by phil-blain** [comment]
@eclare108213 `ice_init::input_data` calls `icepack_init_parameters`, so I think the values are correctly passed to Icepack. Wether to also add these to the Icepack namelist would need another PR.

**Comment by eclare108213** [comment]
Great, thanks.

**Comment by phil-blain** [comment]
thanks @eclare108213, I just added `N/m` for Pstar.

**Comment by apcraig** [comment]
Regression testing looks fine, https://github.com/CICE-Consortium/Test-Results/wiki/cice_by_hash_forks#b2633ec3ef470a332d4e63d9d4b3736c9eeee12c.  I will merge

**Pull request merged**
