### PR TITLE
Update plotting routines in QC script

### PR DESCRIPTION
**Pull request by mattdturner**
## PR checklist
- [x] Short (1 sentence) summary of your PR: 
    Fix an issue where the 2-stage failure map had a flipped x-axis map.  Also add new plotting capability.
- [x] Developer(s): 
    @mattdturner 
- [ ] Suggest PR reviewers from list in the column to the right.
- [x] Please copy the PR test results link or provide a summary of testing completed below.
    Tested the QC script plotting capability on 4 datasets on 1 server.
- How much do the PR code changes differ from the unmodified code? 
    - [x] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [x] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [x] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/.)
    - [ ] Yes
    - [x] No, does the documentation need to be updated at a later time?
        - [x] Yes
        - [ ] No 
- [x] Please provide any additional information or relevant details below:

### CODE REVIEW

**Comment by mattdturner** [comment]
The documentation has not been updated yet.  I wanted some feedback on the capability that is being added before updating documentation.  This PR adds a new `--plot` option that will plot the mean ice thickness in a spatial map, similar to the figures below.  It creates plots for the baseline dataset, test dataset, as well as the difference.

image

image

image

This addition of plotting might potentially address a portion of #347

**Comment by apcraig** [comment]
Is there a reason not to have the --plot option on all the time?

The plots look a bit odd with the whitespace between data, but I assume that's an artifact of the plotting package, correct?

These plots are in addition to a plot of the pass/fail status per gridcell?

**Comment by eclare108213** [comment]
This is super helpful, thanks!

**Comment by mattdturner** [comment]
Yeah, the whitespace is a result of the fact that I am using the `scatter` function to create the plots.  I could set up the script to create filled contour plots:

image

or pcolor plots:

image

Or, I could also setup the script to allow all 3 and have the user select which one with an optional argument (while setting a default if no argument is passed).  If this were solely a plotting script, I would likely do that.  However, I'm not sure if we want plotting-specific command line options for a script whose main functionality is to do the QC test.  I wonder if that might get confusing...

I originally set it up to have plotting as an option because I thought that plots would only be desired if tests failed.  I could set it to always plot the ice thickness data, and just include it in a `try` block so that the script continues if the plotting fails (i.e., if the user doesn't have the necessary Python packages).

And yes, this is in addition to the plot of pass/fail grid cells for the 2-stage test

**Comment by apcraig** [comment]
This all is great.  I am fine with any of the plotting options as the default.  I guess I like pcolor the most (but just one opinion) and I would probably turn on the --plot all the time with a package check.  But I'm also happy to merge the PR now.

**Comment by mattdturner** [comment]
I'll have to update the documentation prior to merging the code.  I'll go ahead and do that today and let you know when its ready.

**Comment by mattdturner** [comment]
I added a brief paragraph to the documentation that mentions the plotting capability.  I also modified the script to always attempt to plot the data (I removed the `--plot` option), and added a new `--plot_type` argument that accepts "scatter", "contour", or "pcolor" (with "pcolor" set as the default).

**Comment by dabail10** [comment]
This script is dying on cheyenne with X window related errors. Is there a python version issue here or do I need to do something different with my X window environment?

Dave

**Pull request merged**
