### PR TITLE
Updating CICE doc structure

### PR DESCRIPTION
**Pull request by duvivier**
Updating CICE documentation to have same structure as Icepack.

Developer(s): Alice
Are the code changes bit for bit, different at roundoff level, or more substantial? bit for bit
Is the documentation being updated with this PR? (Y/N) Y
If not, does the documentation need to be updated separately? (Y/N) N
"Documentation" includes information on the wiki and .rst files in doc/source/, 
which are used to create the online technical docs at https://cice-consortium.github.io/CICE/ 
Please suggest code reviewers in the column at right. 
Other Relevant Details:

I wanted to organize this roughly the same way as Icepack, so I've broken up the documentation into sections the way we did for icepack. There still needs to be significant changes to the documentation (e.g. figure labeling, section referencing), but now we can all work on the same documents the way they should be done.

I also updated all the script to cice.setup instead of create.case as per Issue #77

### CODE REVIEW

**Comment by duvivier** [comment]
@apcraig Also, it doesn't look like we have Travis-CI working yet with CICE, is that correct?

**Comment by apcraig** [comment]
Correct, travis is not yet setup with CICE.  There are many things we need to review and do with CICE at this point to "get it up to date".

**Comment by duvivier** [comment]
Okay, thanks @apcraig . I just wanted to be sure since I did the PR and there was no automatic testing that could test if things are broken (though I only touched the documentation *rst files, so this shouldn't be an issue).

**Comment by apcraig** [comment]
The documentation definitely needs a thorough review with respect to using the scripts.  I think the CICE scripts were updated but the documentation hasn't been yet.  I can take that on if you like.  We could migrate the Icepack documentation to CICE then revise as needed.  Or we can just rewrite what we've got in CICE.

**Comment by eclare108213** [comment]
Here are some additional items I noticed that need to be changed, but not necessarily before this PR is merged:

> user_suide/ug_performance.rst:  the test setup information should be put somewhere else.  Is this duplicated in user_guide/ug_testing.rst?  If so, just delete it here.

> user_guid/ug_running.rst:  this is very old info, from cice v5!  Maybe this is where to put setup info that's currently in ug_performance?  We need to keep the table of environment variables.

> user_guide/ug_testing.rst:   update the cice.setup flags and remove the version/date line at the top

> user_guide/ug_troubleshooting.rst:  this is v5 info — update to v6

> Many of the new files contain text specific to Icepack, which needs to be changed for CICE.  E.g.
> developer_guide/dg_about.rst, dg_driver.rst, dg_scripts.rst

> remove all references to drupal

**Comment by apcraig** [comment]
Also, I think this could be a few step process and doesn't all need to happen in one PR.  There are several tasks that need to be done before CICE is "more ready" including travis, documentation, further testing, and so forth.  We need to look thru the outstanding issues as well.

**Comment by duvivier** [comment]
@apcraig @eclare108213 I have made the changes that Elizabeth lists as necessary but *not* the additional items yet. I just wanted to get this structure into the repo so that we are all working with the same format. Once we have that in there I think we will need to go through it with a fine tooth comb and re-do it. Basically what was there before is just what we decided was part of "CICE" as opposed to "Icepack" when Elizabeth and I did the initial separation. There will be lots of tweaking to do to this as we get ready for the real release so I think there will be a number of PRs to finish it all. I've made note of Elizabeth's comments above to include soon in a PR update.

**Comment by eclare108213** [comment]
Thanks @duvivier !

**Pull request merged**
