### PR TITLE
Add noaa machines and minor cleanup from RG

### PR DESCRIPTION
**Pull request by apcraig**
Add NOAA machines and some cleanup, from @rgrumbine, see #317 
Additions to run regression tests on NWS operational system 'phase2' and NOAA R+D system 'theia':

- Developer(s): rgrumbine, tcraig

- Are the code changes bit for bit, different at roundoff level, or more substantial? bit-for-bit

- Does this PR create or have dependencies on Icepack or any other models?  N

- Is the documentation being updated with this PR? (Y/N) N
If not, does the documentation need to be updated separately at a later time? (Y/N) N

- Other Relevant Details:

Though present, the theia_gnu and theia_pgi configurations have not been confirmed to pass the full regression suite.

This was a redo of PR #317 which caused problems due to some issues with the Icepack submodule setup.  This is exactly f9ae148f37990d2b5f80 from @rgrumbine's fork with the icepack submodule changes not brought over and the gitignore mod not included.  It also includes few other mods to get rid of tabs in a few files that were noticed the sandbox was reviewed before committing.

### CODE REVIEW

**Comment by apcraig** [comment]
I am running a quick test on conrad as well.  I will report those results when I have them.  But wanted to give @rgrumbine a chance to review this PR and for travis to do it's thing concurrently.

**Comment by apcraig** [comment]
I am going to close #317 at this point.

**Comment by rgrumbine** [comment]
Thanks Tony.

**Comment by apcraig** [comment]
Just to add, full test suite on conrad showed no problems.

**Pull request merged**
