### PR TITLE
Update documentation including qc, debugger, and namelist table

### PR DESCRIPTION
**Pull request by apcraig**
## PR checklist
- [X] Short (1 sentence) summary of your PR: 
    Update documentation including qc, debugger, and namelist table
- [X] Developer(s): 
    apcraig
- [X] Suggest PR reviewers from list in the column to the right.
- [X] Please copy the PR test results link or provide a summary of testing completed below.
    Ran quick suites on cheyenne with 3 compilers, all bit-for-bit.  Code changes are minimal.
  https://github.com/CICE-Consortium/Test-Results/wiki/cice_by_hash_forks#2054d0984a4a0eb1293e9fd3266bf3dbbd45753e
- How much do the PR code changes differ from the unmodified code? 
    - [X] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [X] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [X] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [X] Yes
    - [ ] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [ ] No 
- [X] Please provide any additional information or relevant details below:

Also added checks for ncat, nilyr, nslyr, nblyr and modified the abort flags implementation in ice_init converting from namelist to character string to be able to identify multiple failures with the abort_list variable.

Addresses issues #441, #412, #375, #347, #166 at least partly.

### CODE REVIEW

**Comment by apcraig** [comment]
There are some obvious issues in the namelist tables. I'm working to fix them.

**Comment by apcraig** [comment]
OK, I think the table is fixed.  I took it offline to debug and review.  @eclare108213, let me know what you think.

**Comment by apcraig** [comment]
Thanks @eclare108213, I have update 3.4.1 and 3.4.2 as suggested and will merge in the next day unless there are other comments.  I will work on the same changes in Icepack next.

**Comment by eclare108213** [comment]
I just noticed that in the case settings table, kdyn=1 occurs twice.  Please, would you remove the one that says "dynamics ON" and keep the one that says evp?

**Comment by apcraig** [comment]
@eclare108213, I'm not seeing the kdyn issue.  Are you looking at the latest table?  

https://cice-consortium-cice--459.org.readthedocs.build/en/459/user_guide/ug_case_settings.html#dynamics-nml

**Comment by eclare108213** [comment]
I was looking at the docs on master.  Looks like you already took care of it.  Thanks!

**Pull request merged**
