### PR TITLE
Fix for rare instability in (probabilistic) seabed stress

### PR DESCRIPTION
**Pull request by JFLemieux73**
For detailed information about submitting Pull Requests (PRs) to the CICE-Consortium,
please refer to: <https://github.com/CICE-Consortium/About-Us/wiki/Resource-Index#information-for-developers>

## PR checklist
- [x] Short (1 sentence) summary of your PR: 
    Fix rare instability in probabilistic seabed stress (log of negative number). 
- [x] Developer(s): 
    K. Hedstrom, E. Hunke
- [x] Suggest PR reviewers from list in the column to the right.
   @eclare108213 
- [x] Please copy the PR test results link or provide a summary of testing completed below.
     262 measured results of 262 total results
     262 of 262 tests PASSED
     0 of 262 tests PENDING
     0 of 262 tests MISSING data
     0 of 262 tests FAILED

All tests are BFB including the ones with probabilistic seabed stress. The old code had v_i = v_i - m_i**2 and the new one has v_i = max((v_i - m_i**2), puny). It looks like  v_i - m_i**2 is always larger than puny in the tests of the base suite. Longer simulations could lead to small differences. 

- How much do the PR code changes differ from the unmodified code? 
    - [x] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [x] No
- Does this PR update the Icepack submodule?  If so, the Icepack submodule must point to a hash on Icepack's main branch.
    - [ ] Yes
    - [x] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [x] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [x] Yes
    - [ ] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [ ] No
    The only thing that was modified is the reference for the Dupont et al. paper which has been published.  
- [x] Please provide any additional information or relevant details below:
This PR replaces PR #808.

### CODE REVIEW

**Comment by phil-blain** [comment]
> Developer(s):
> K. Hedstrom, E. Hunke

my personal preference would be to credit Kate and Elizabeth in the commit authorship, or at least using a `Co-authored-by:` trailer in the commit message  :)

**Comment by eclare108213** [comment]
readthedocs failed but it seems to be on the clone, not necessarily a problem with the changes.  Can this be relaunched somehow?

**Review by eclare108213 — COMMENTED** [review]
These changes look good to me.  @kshedstrom, can you check whether this fixes the failure in your run?

**Comment by eclare108213** [comment]
I see how to rerun GHActions but not readthedocs.  Might have to re-commit and push as @phil-blain suggests.

**Comment by apcraig** [comment]
I also don't see how to restart the readthedocs manually, will google later, but feel free to force push an update to the branch.  thanks.

**Comment by kshedstrom** [comment]
Yes, this version works for me.

**Comment by JFLemieux73** [comment]
I am not sure I follow this...should I just do what Philippe proposes?

git commit --amend --no-edit
git push --force

**Comment by eclare108213** [comment]
Yes, give it a shot and see if it makes the readthedocs check work correctly.

**Review by eclare108213 — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
