### PR TITLE
Update CICE with CMIP changes.

### PR DESCRIPTION
**Pull request by dabail10**
This PR includes the following. Note these rely on the CMIP updates from Icepack as well.

1. Update all of the CMIP history variables #93 

2. Update evaporation over snow and bare ice. #97 

3. Also, some uninitialized variables. #63 

4. Adds gravit to ice_dyn_shared.F90 when #coupled is activated. #159 

There is a new history namelist flag f_CMIP that activates all of the CMIP history in one go.

- Developer(s): D. Bailey

- Please suggest code Pull Request reviewers in the column at right.

- Are the code changes bit for bit, different at roundoff level, or more substantial? BFB

- Is the documentation being updated with this PR? (Y/N) N
If not, does the documentation need to be updated separately at a later time? (Y/N) Y
Note: "Documentation" includes information on the wiki and .rst files in doc/source/, 
which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/.

- Other Relevant Details:

### CODE REVIEW

**Comment by dabail10** [comment]
Ok. I redid the istat changes in ice_distribution.F90. I think that was all that was different from dummy2?

Dave

**Comment by apcraig** [comment]
@dabail10, Manually fixing things seem dangerous.  Very easy to miss something.  Can we try the other options to see if any of them result in a cleaner PR "automatically".  I'm happy to try to if you don't have time.

**Comment by dabail10** [comment]
I'll check into this.

**Comment by dabail10** [comment]
Ok. I have gone through the changes in this CMIP tag. Everything is bfb.

1. Everything in ice_history_shared.F90, ice_history_write.F90 and ice_history.F90 is necessary for CMIP variables.

2. The changes in ice_dyn_shared.F90 resolve the issue of the variable "gravit" not being available when the "coupled" flag is on.

3. The module ice_flux.F90 required a number of initialized variables for history purposes (ffbot, frzmlt_init, fswint_ai, fpond, Cdn_atm_ratio, and strength). Also in ice_flux.F90, the new variables for CMIP purposes and evaporation over snow and bare ice are required (Tsnice, evapi, evaps, fcondbot, fcondbotn). Finally, fswfac is no longer used. I simply removed it and am using "scale_factor" instead.

4. In ice_step_mod.F90, the initial band albedos (alvdr_init, etc) need to be initialized. Also, the new CMIP related variables are required here. Additionally, the computations in the mixed layer do need the ghost cells otherwise resulting in uninitialized variables.

5. In ice_grid.F90, I have added initialization for latu_bounds and lonu_bounds. This is mainly for history writing.

6. In CICE_RunMod.F90, coupling_prep does not need to be in the ghost cells. This causes uninitialized problems.

I think that is it!

**Comment by dabail10** [comment]
Note this tag has dependencies on Icepack and requires the CMIP update there as well.

**Comment by apcraig** [comment]
OK, I'm going to run a series of tests myself.  Should we close the cmip2 PR?

**Comment by dabail10** [comment]
Yes. I will close that.

**Pull request merged**
